# -*- coding: utf-8 -*-
"""Gera src/04_movies_avancado.ipynb — LSTM + BERT (Bertimbau) replicando V1..V5 do notebook 03."""
import nbformat as nbf
import io, os

nb = nbf.v4.new_notebook()
nb.metadata = {
    "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
    "language_info": {"name": "python", "version": "3.10"}
}

cells = []

# ============================================================
# Célula 0 — Markdown título e overview
# ============================================================
cells.append(nbf.v4.new_markdown_cell(
    "# Notebook 04 — Modelos Avançados (LSTM + BERT/Bertimbau) · Movies\n\n"
    "Replica as **5 visões** do notebook 03 com modelos de **deep learning**:\n\n"
    "- **LSTM** (PyTorch) — embeddings aprendidos do zero\n"
    "- **BERT (Bertimbau base)** — `neuralmind/bert-base-portuguese-cased`, fine-tuning\n\n"
    "Objetivo: contrastar **técnicas básicas** (NB/LR/SVM do notebook 03) com **técnicas avançadas** "
    "para mostrar se o reality gap (V3/V5) persiste com modelos contextuais.\n\n"
    "## ⚠️ Pré-requisitos\n\n"
    "1. **PyTorch com CUDA** instalado (RTX 3000+ recomendado):\n"
    "   ```bash\n"
    "   pip install torch --index-url https://download.pytorch.org/whl/cu121\n"
    "   pip install transformers accelerate tqdm\n"
    "   ```\n"
    "2. **Verificar GPU:** `python -c \"import torch; print(torch.cuda.is_available())\"`  → deve retornar `True`\n"
    "3. **Dataset real** (já baixado pelo notebook 03 via kagglehub).\n\n"
    "## ⏱️ Tempo esperado (RTX 3070, 8GB VRAM)\n\n"
    "| Etapa | Tempo |\n"
    "|---|---|\n"
    "| LSTM em V1/V2/V3/V5 (visões pequenas) | ~5 min total |\n"
    "| LSTM em V4 (1.2M frases) | ~30-60 min |\n"
    "| BERT em V1/V2/V3/V5 (visões pequenas) | ~10 min total |\n"
    "| BERT em V4 (1.2M frases, 3 epochs) | **~6-9 HORAS** ⚠️ |\n"
    "| **Total (rodando overnight)** | **~7-10 horas** |\n\n"
    "Se for testar primeiro, ajuste `MAX_SAMPLES_REAL = 100_000` na célula de constantes."
))

# ============================================================
# Célula 1 — Setup padrão (mesma da notebook 03) + GPU detection
# ============================================================
cells.append(nbf.v4.new_code_cell(
    "# ============================================================\n"
    "# CÉLULA 1 — SETUP PADRÃO + DETECÇÃO DE GPU\n"
    "# ============================================================\n"
    "import os, sys, shutil, re, time, json\n"
    "import numpy as np\n"
    "import pandas as pd\n"
    "\n"
    "# Reprodutibilidade\n"
    "SEED = 42\n"
    "np.random.seed(SEED)\n"
    "\n"
    "# Detecção de ambiente (igual ao notebook 03)\n"
    "IN_COLAB = 'google.colab' in sys.modules\n"
    "\n"
    "if IN_COLAB:\n"
    "    if not os.path.exists('/content/tcc-analise-sentimento'):\n"
    "        os.system('git clone https://github.com/ROMAUSKI/tcc-analise-sentimento.git /content/tcc-analise-sentimento')\n"
    "    else:\n"
    "        os.system('cd /content/tcc-analise-sentimento && git pull')\n"
    "    BASE_DIR = '/content/tcc-analise-sentimento'\n"
    "    REAL_DATA_PATH = '/content/sample_data/dataset_real_sentimentos'\n"
    "else:\n"
    "    BASE_DIR = os.path.abspath(os.path.join(os.getcwd(), '..'))\n"
    "    REAL_DATA_PATH = os.path.join(BASE_DIR, 'src', 'dados_reais')\n"
    "\n"
    "if not os.path.exists(REAL_DATA_PATH) or not os.listdir(REAL_DATA_PATH):\n"
    "    import kagglehub\n"
    "    print('Baixando dataset real do Kaggle (~877 MB, só na 1ª vez)...')\n"
    "    cache_path = kagglehub.dataset_download('fredericods/ptbr-sentiment-analysis-datasets')\n"
    "    os.makedirs(REAL_DATA_PATH, exist_ok=True)\n"
    "    for f in os.listdir(cache_path):\n"
    "        shutil.copy(os.path.join(cache_path, f), os.path.join(REAL_DATA_PATH, f))\n"
    "    print(f'Dataset real disponível em: {REAL_DATA_PATH}')\n"
    "else:\n"
    "    print(f'Dataset real já existe em: {REAL_DATA_PATH}')\n"
    "\n"
    "DADOS_BRUTOS_MOVIES = os.path.join(BASE_DIR, 'dados', 'brutos')\n"
    "DADOS_BRUTOS_APPS   = os.path.join(BASE_DIR, 'dados', 'brutos_apps')\n"
    "DADOS_PROCESSADO    = os.path.join(BASE_DIR, 'dados', 'processado')\n"
    "RESULTADOS          = os.path.join(BASE_DIR, 'resultados')\n"
    "CHECKPOINTS         = os.path.join(BASE_DIR, 'src', 'checkpoints_avancado')\n"
    "os.makedirs(CHECKPOINTS, exist_ok=True)\n"
    "\n"
    "# --- PyTorch + GPU detection ---\n"
    "import torch\n"
    "torch.manual_seed(SEED)\n"
    "if torch.cuda.is_available():\n"
    "    torch.cuda.manual_seed_all(SEED)\n"
    "    DEVICE = torch.device('cuda')\n"
    "    GPU_NAME = torch.cuda.get_device_name(0)\n"
    "    GPU_VRAM = torch.cuda.get_device_properties(0).total_memory / 1e9\n"
    "    print(f'✅ GPU detectada: {GPU_NAME} ({GPU_VRAM:.1f} GB VRAM)')\n"
    "else:\n"
    "    DEVICE = torch.device('cpu')\n"
    "    GPU_NAME = 'CPU (sem GPU)'\n"
    "    print('⚠️ ATENÇÃO: nenhuma GPU detectada. Treinar BERT em CPU é INVIÁVEL (semanas).')\n"
    "    print('   Recomendado: instalar PyTorch com CUDA OU executar este notebook no Google Colab com runtime GPU T4.')\n"
    "\n"
    "print(f'\\nAmbiente: {\"Colab\" if IN_COLAB else \"Local\"}')\n"
    "print(f'PyTorch: {torch.__version__}')\n"
    "print(f'CUDA disponível: {torch.cuda.is_available()}')\n"
    "print(f'BASE_DIR: {BASE_DIR}')\n"
))

# ============================================================
# Célula 2 — Markdown configurações
# ============================================================
cells.append(nbf.v4.new_markdown_cell(
    "## Configurações principais\n\n"
    "Ajuste estas constantes **antes** de executar. Ordem de impacto no tempo total:\n\n"
    "1. `MAX_SAMPLES_REAL` — `None` para tudo (~1.5M, demora horas), `100_000` para teste rápido\n"
    "2. `BERT_EPOCHS` — 3 é o padrão da literatura, 2 corta tempo pela metade\n"
    "3. `BERT_BATCH_SIZE` — aumentar para acelerar (até estourar VRAM); diminuir se OOM\n"
    "4. `LSTM_EPOCHS` — 5 é OK; mais que 10 tende a overfitar com 480 frases (V1/V2/V3)"
))

# ============================================================
# Célula 3 — Constantes configuráveis
# ============================================================
cells.append(nbf.v4.new_code_cell(
    "# ============================================================\n"
    "# CÉLULA 3 — CONSTANTES (ajuste conforme tempo disponível)\n"
    "# ============================================================\n"
    "\n"
    "# --- Volume do dataset real (V4 e V5 usam) ---\n"
    "MAX_SAMPLES_REAL = None         # None = TODOS (~1.5M, demora HORAS); 100_000 = teste rápido\n"
    "\n"
    "# --- LSTM ---\n"
    "LSTM_EMBEDDING_DIM = 128\n"
    "LSTM_HIDDEN_DIM    = 128\n"
    "LSTM_EPOCHS        = 5\n"
    "LSTM_BATCH_SIZE    = 32\n"
    "LSTM_LR            = 1e-3\n"
    "LSTM_DROPOUT       = 0.3\n"
    "LSTM_MAX_LEN       = 100   # tokens por frase (truncar/padding)\n"
    "\n"
    "# --- BERT (Bertimbau base) ---\n"
    "BERT_MODEL_NAME    = 'neuralmind/bert-base-portuguese-cased'\n"
    "BERT_EPOCHS        = 3\n"
    "BERT_BATCH_SIZE    = 16        # se OOM na 3070, reduzir para 8\n"
    "BERT_MAX_LENGTH    = 128       # tokens (subwords) por frase\n"
    "BERT_LR            = 2e-5\n"
    "BERT_WEIGHT_DECAY  = 0.01\n"
    "\n"
    "# --- Sintético (volume controlado, mesmo do notebook 03) ---\n"
    "N_POR_CLASSE_SINT = 200\n"
    "\n"
    "print('Configurações:')\n"
    "print(f'  MAX_SAMPLES_REAL: {MAX_SAMPLES_REAL if MAX_SAMPLES_REAL else \"TODOS (~1.5M)\"}')\n"
    "print(f'  BERT: {BERT_MODEL_NAME}')\n"
    "print(f'  BERT epochs={BERT_EPOCHS}, batch={BERT_BATCH_SIZE}, max_len={BERT_MAX_LENGTH}')\n"
    "print(f'  LSTM epochs={LSTM_EPOCHS}, batch={LSTM_BATCH_SIZE}, hidden={LSTM_HIDDEN_DIM}')\n"
))

# ============================================================
# Célula 4 — Markdown carregar dados
# ============================================================
cells.append(nbf.v4.new_markdown_cell(
    "## 1. Carregar dados (sintético + real balanceado + real desbalanceado) e preparar splits\n\n"
    "Reusa exatamente a mesma lógica do notebook 03 para garantir comparabilidade dos resultados."
))

# ============================================================
# Célula 5 — Carregar dados
# ============================================================
cells.append(nbf.v4.new_code_cell(
    "# ============================================================\n"
    "# CÉLULA 5 — Carregar dados (mesmas regras do notebook 03)\n"
    "# ============================================================\n"
    "from sklearn.model_selection import train_test_split\n"
    "\n"
    "def limpar_texto(texto):\n"
    "    texto = str(texto).lower()\n"
    "    texto = re.sub(r'[^a-zà-ÿ\\s]', '', texto)\n"
    "    texto = re.sub(r'\\s+', ' ', texto).strip()\n"
    "    return texto\n"
    "\n"
    "# --- Sintético (200/classe) ---\n"
    "df_sintetico = pd.read_csv(os.path.join(DADOS_PROCESSADO, 'synthetic_dataset.csv'))\n"
    "df_sintetico = df_sintetico[['frase_limpa', 'classe', 'fonte']].dropna()\n"
    "df_sintetico_bal = (df_sintetico.groupby('classe')\n"
    "                                .sample(n=N_POR_CLASSE_SINT, random_state=SEED)\n"
    "                                .reset_index(drop=True))\n"
    "print(f'Sintético: {len(df_sintetico_bal)} frases ({N_POR_CLASSE_SINT}/classe)')\n"
    "\n"
    "# --- Real ---\n"
    "path_real = os.path.join(REAL_DATA_PATH, 'utlc_movies.csv')\n"
    "print(f'\\nCarregando dataset real (MAX_SAMPLES_REAL={MAX_SAMPLES_REAL})...')\n"
    "t0 = time.time()\n"
    "df_real_raw = pd.read_csv(path_real, nrows=MAX_SAMPLES_REAL)\n"
    "print(f'  {len(df_real_raw):,} linhas carregadas em {time.time()-t0:.1f}s')\n"
    "\n"
    "def rating_para_classe(rating):\n"
    "    if rating >= 4: return 'Positiva'\n"
    "    elif rating <= 2: return 'Negativa'\n"
    "    else: return 'Neutra'\n"
    "\n"
    "df_real_raw['classe'] = df_real_raw['rating'].apply(rating_para_classe)\n"
    "df_real = df_real_raw[['review_text', 'classe']].dropna().rename(columns={'review_text': 'frase'})\n"
    "df_real['frase_limpa'] = df_real['frase'].apply(limpar_texto)\n"
    "df_real = df_real[df_real['frase_limpa'] != ''].reset_index(drop=True)\n"
    "print(f'Real (após limpeza): {len(df_real):,} frases')\n"
    "\n"
    "# --- Real BALANCEADO (200/classe) ---\n"
    "df_real_bal = (df_real.groupby('classe')\n"
    "                      .sample(n=N_POR_CLASSE_SINT, random_state=SEED)\n"
    "                      .reset_index(drop=True))\n"
    "print(f'Real balanceado: {len(df_real_bal)} frases ({N_POR_CLASSE_SINT}/classe)')\n"
    "\n"
    "# --- Real DESBALANCEADO (todos) ---\n"
    "df_real_desbal = df_real.copy().reset_index(drop=True)\n"
    "print(f'Real desbalanceado: {len(df_real_desbal):,} frases')\n"
    "print(df_real_desbal['classe'].value_counts(normalize=True).round(3))\n"
    "\n"
    "# --- Splits 80/20 estratificados (5 visões) ---\n"
    "S_tr, S_te = train_test_split(df_sintetico_bal, test_size=0.2, stratify=df_sintetico_bal['classe'], random_state=SEED)\n"
    "R_tr, R_te = train_test_split(df_real_bal,      test_size=0.2, stratify=df_real_bal['classe'],      random_state=SEED)\n"
    "RD_tr, RD_te = train_test_split(df_real_desbal, test_size=0.2, stratify=df_real_desbal['classe'], random_state=SEED)\n"
    "\n"
    "print(f'\\nSplits:')\n"
    "print(f'  V1: Sintético→Sintético — {len(S_tr)} treino / {len(S_te)} teste')\n"
    "print(f'  V2: Real(bal)→Real(bal) — {len(R_tr)} treino / {len(R_te)} teste')\n"
    "print(f'  V3: Sintético→Real(bal) — usa S_tr para treino e R_te para teste')\n"
    "print(f'  V4: Real(desbal)→Real(desbal) — {len(RD_tr):,} treino / {len(RD_te):,} teste')\n"
    "print(f'  V5: Sintético→Real(desbal) — usa S_tr para treino e RD_te para teste')\n"
))

# ============================================================
# Célula 6 — Markdown LSTM
# ============================================================
cells.append(nbf.v4.new_markdown_cell(
    "## 2. LSTM — definição e treino\n\n"
    "Embeddings aprendidos do zero (sem pré-treino). 1 camada LSTM unidirecional.\n"
    "Vocabulário **construído no treino de cada visão** (palavras não vistas viram `<UNK>`)."
))

# ============================================================
# Célula 7 — LSTM definição (modelo + helpers)
# ============================================================
cells.append(nbf.v4.new_code_cell(
    "# ============================================================\n"
    "# CÉLULA 7 — LSTM: arquitetura + helpers de tokenização\n"
    "# ============================================================\n"
    "import torch.nn as nn\n"
    "from torch.utils.data import Dataset, DataLoader\n"
    "from collections import Counter\n"
    "\n"
    "PAD, UNK = 0, 1\n"
    "\n"
    "def tokenize(texto):\n"
    "    \"\"\"Tokenização simples por palavra (split em espaço)\"\"\"\n"
    "    return texto.split()\n"
    "\n"
    "def build_vocab(textos, min_freq=1, max_size=20000):\n"
    "    \"\"\"Constrói vocabulário com índices reservados PAD=0, UNK=1\"\"\"\n"
    "    counter = Counter()\n"
    "    for t in textos:\n"
    "        counter.update(tokenize(t))\n"
    "    vocab = {'<PAD>': PAD, '<UNK>': UNK}\n"
    "    for word, freq in counter.most_common(max_size - 2):\n"
    "        if freq >= min_freq:\n"
    "            vocab[word] = len(vocab)\n"
    "    return vocab\n"
    "\n"
    "def encode(texto, vocab, max_len):\n"
    "    \"\"\"Converte texto em lista de índices, padded/truncated para max_len\"\"\"\n"
    "    ids = [vocab.get(w, UNK) for w in tokenize(texto)[:max_len]]\n"
    "    length = len(ids)\n"
    "    ids = ids + [PAD] * (max_len - length)\n"
    "    return ids, length\n"
    "\n"
    "class TextDataset(Dataset):\n"
    "    def __init__(self, textos, labels, vocab, max_len):\n"
    "        self.data = [encode(t, vocab, max_len) for t in textos]\n"
    "        self.labels = labels.values if hasattr(labels, 'values') else list(labels)\n"
    "    def __len__(self): return len(self.data)\n"
    "    def __getitem__(self, idx):\n"
    "        ids, length = self.data[idx]\n"
    "        return torch.tensor(ids, dtype=torch.long), torch.tensor(length, dtype=torch.long), self.labels[idx]\n"
    "\n"
    "class LSTMClassifier(nn.Module):\n"
    "    def __init__(self, vocab_size, embed_dim, hidden_dim, num_classes, dropout):\n"
    "        super().__init__()\n"
    "        self.embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=PAD)\n"
    "        self.lstm = nn.LSTM(embed_dim, hidden_dim, batch_first=True)\n"
    "        self.dropout = nn.Dropout(dropout)\n"
    "        self.fc = nn.Linear(hidden_dim, num_classes)\n"
    "    def forward(self, x, lengths):\n"
    "        emb = self.embedding(x)\n"
    "        packed = nn.utils.rnn.pack_padded_sequence(emb, lengths.cpu(), batch_first=True, enforce_sorted=False)\n"
    "        _, (h, _) = self.lstm(packed)\n"
    "        h = self.dropout(h.squeeze(0))\n"
    "        return self.fc(h)\n"
    "\n"
    "print('LSTM definido. Pronto para treino.')\n"
))

# ============================================================
# Célula 8 — Função de treino e avaliação LSTM (genérica por visão)
# ============================================================
cells.append(nbf.v4.new_code_cell(
    "# ============================================================\n"
    "# CÉLULA 8 — Função run_lstm_vision(X_tr, y_tr, X_te, y_te, visao_nome)\n"
    "# ============================================================\n"
    "from sklearn.preprocessing import LabelEncoder\n"
    "from sklearn.metrics import accuracy_score, precision_recall_fscore_support, f1_score\n"
    "\n"
    "def run_lstm_vision(X_tr, y_tr, X_te, y_te, visao_nome):\n"
    "    print(f'\\n=== LSTM | {visao_nome} ===')\n"
    "    t0 = time.time()\n"
    "    le = LabelEncoder()\n"
    "    y_tr_enc = le.fit_transform(y_tr)\n"
    "    y_te_enc = le.transform(y_te)\n"
    "    num_classes = len(le.classes_)\n"
    "\n"
    "    vocab = build_vocab(X_tr, min_freq=1, max_size=20000)\n"
    "    print(f'  Vocabulário: {len(vocab):,} tokens')\n"
    "\n"
    "    train_ds = TextDataset(X_tr.tolist() if hasattr(X_tr, \"tolist\") else list(X_tr),\n"
    "                            pd.Series(y_tr_enc), vocab, LSTM_MAX_LEN)\n"
    "    test_ds  = TextDataset(X_te.tolist() if hasattr(X_te, \"tolist\") else list(X_te),\n"
    "                            pd.Series(y_te_enc), vocab, LSTM_MAX_LEN)\n"
    "    train_loader = DataLoader(train_ds, batch_size=LSTM_BATCH_SIZE, shuffle=True)\n"
    "    test_loader  = DataLoader(test_ds,  batch_size=LSTM_BATCH_SIZE, shuffle=False)\n"
    "\n"
    "    model = LSTMClassifier(len(vocab), LSTM_EMBEDDING_DIM, LSTM_HIDDEN_DIM, num_classes, LSTM_DROPOUT).to(DEVICE)\n"
    "    optimizer = torch.optim.AdamW(model.parameters(), lr=LSTM_LR)\n"
    "    criterion = nn.CrossEntropyLoss()\n"
    "\n"
    "    for epoch in range(LSTM_EPOCHS):\n"
    "        model.train()\n"
    "        total_loss = 0\n"
    "        for ids, lengths, labels in train_loader:\n"
    "            ids, lengths, labels = ids.to(DEVICE), lengths.to(DEVICE), labels.to(DEVICE).long()\n"
    "            optimizer.zero_grad()\n"
    "            logits = model(ids, lengths)\n"
    "            loss = criterion(logits, labels)\n"
    "            loss.backward()\n"
    "            optimizer.step()\n"
    "            total_loss += loss.item() * labels.size(0)\n"
    "        print(f'  Epoch {epoch+1}/{LSTM_EPOCHS} | loss={total_loss/len(train_ds):.4f}')\n"
    "\n"
    "    # Avaliação\n"
    "    model.eval()\n"
    "    preds, trues = [], []\n"
    "    with torch.no_grad():\n"
    "        for ids, lengths, labels in test_loader:\n"
    "            ids, lengths = ids.to(DEVICE), lengths.to(DEVICE)\n"
    "            logits = model(ids, lengths)\n"
    "            preds.extend(logits.argmax(dim=1).cpu().numpy())\n"
    "            trues.extend(labels.numpy())\n"
    "\n"
    "    acc = accuracy_score(trues, preds)\n"
    "    prec, rec, f1w, _ = precision_recall_fscore_support(trues, preds, average='weighted', zero_division=0)\n"
    "    f1m = f1_score(trues, preds, average='macro', zero_division=0)\n"
    "    elapsed = time.time() - t0\n"
    "    print(f'  ✓ LSTM | F1w={f1w:.2%}  F1macro={f1m:.2%}  Acc={acc:.2%}  ({elapsed:.0f}s)')\n"
    "\n"
    "    return {'Visão': visao_nome, 'Modelo': 'LSTM',\n"
    "            'Acurácia': acc, 'Precisão': prec, 'Recall': rec,\n"
    "            'F1-Score': f1w, 'F1-Macro': f1m, 'Tempo (s)': round(elapsed, 1)}\n"
))

# ============================================================
# Célula 9 — Markdown BERT
# ============================================================
cells.append(nbf.v4.new_markdown_cell(
    "## 3. BERT (Bertimbau) — fine-tuning\n\n"
    "Usa `neuralmind/bert-base-portuguese-cased` (110M parâmetros, ~440MB de download na 1ª vez).\n"
    "Fine-tuning supervisionado com `transformers.Trainer`."
))

# ============================================================
# Célula 10 — BERT preparação (tokenizer)
# ============================================================
cells.append(nbf.v4.new_code_cell(
    "# ============================================================\n"
    "# CÉLULA 10 — BERT: tokenizer + dataset\n"
    "# ============================================================\n"
    "from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments\n"
    "from transformers import DataCollatorWithPadding\n"
    "\n"
    "print(f'Carregando tokenizer {BERT_MODEL_NAME}...')\n"
    "BERT_TOKENIZER = AutoTokenizer.from_pretrained(BERT_MODEL_NAME)\n"
    "print(f'  vocab_size: {BERT_TOKENIZER.vocab_size}, max_len recomendado: {BERT_TOKENIZER.model_max_length}')\n"
    "\n"
    "class BertDataset(torch.utils.data.Dataset):\n"
    "    def __init__(self, textos, labels, tokenizer, max_length):\n"
    "        self.encodings = tokenizer(\n"
    "            textos.tolist() if hasattr(textos, \"tolist\") else list(textos),\n"
    "            truncation=True, padding=False, max_length=max_length\n"
    "        )\n"
    "        self.labels = labels.values if hasattr(labels, 'values') else list(labels)\n"
    "    def __len__(self): return len(self.labels)\n"
    "    def __getitem__(self, idx):\n"
    "        item = {k: torch.tensor(v[idx]) for k, v in self.encodings.items()}\n"
    "        item['labels'] = torch.tensor(int(self.labels[idx]))\n"
    "        return item\n"
))

# ============================================================
# Célula 11 — BERT função de treino+avaliação
# ============================================================
cells.append(nbf.v4.new_code_cell(
    "# ============================================================\n"
    "# CÉLULA 11 — Função run_bert_vision(X_tr, y_tr, X_te, y_te, visao_nome)\n"
    "# ============================================================\n"
    "import warnings\n"
    "warnings.filterwarnings('ignore')\n"
    "\n"
    "def compute_metrics(eval_pred):\n"
    "    logits, labels = eval_pred\n"
    "    preds = logits.argmax(axis=-1)\n"
    "    acc = accuracy_score(labels, preds)\n"
    "    prec, rec, f1w, _ = precision_recall_fscore_support(labels, preds, average='weighted', zero_division=0)\n"
    "    f1m = f1_score(labels, preds, average='macro', zero_division=0)\n"
    "    return {'accuracy': acc, 'precision': prec, 'recall': rec, 'f1_weighted': f1w, 'f1_macro': f1m}\n"
    "\n"
    "def run_bert_vision(X_tr, y_tr, X_te, y_te, visao_nome):\n"
    "    print(f'\\n=== BERT | {visao_nome} ===')\n"
    "    print(f'  Treino: {len(X_tr):,} frases | Teste: {len(X_te):,} frases')\n"
    "    t0 = time.time()\n"
    "\n"
    "    le = LabelEncoder()\n"
    "    y_tr_enc = le.fit_transform(y_tr)\n"
    "    y_te_enc = le.transform(y_te)\n"
    "    num_classes = len(le.classes_)\n"
    "\n"
    "    train_ds = BertDataset(X_tr, pd.Series(y_tr_enc), BERT_TOKENIZER, BERT_MAX_LENGTH)\n"
    "    test_ds  = BertDataset(X_te, pd.Series(y_te_enc), BERT_TOKENIZER, BERT_MAX_LENGTH)\n"
    "\n"
    "    model = AutoModelForSequenceClassification.from_pretrained(BERT_MODEL_NAME, num_labels=num_classes).to(DEVICE)\n"
    "\n"
    "    safe_name = re.sub(r'[^a-zA-Z0-9]+', '_', visao_nome).lower()\n"
    "    out_dir = os.path.join(CHECKPOINTS, f'bert_{safe_name}')\n"
    "\n"
    "    training_args = TrainingArguments(\n"
    "        output_dir=out_dir,\n"
    "        num_train_epochs=BERT_EPOCHS,\n"
    "        per_device_train_batch_size=BERT_BATCH_SIZE,\n"
    "        per_device_eval_batch_size=BERT_BATCH_SIZE * 2,\n"
    "        learning_rate=BERT_LR,\n"
    "        weight_decay=BERT_WEIGHT_DECAY,\n"
    "        eval_strategy='epoch',\n"
    "        save_strategy='epoch',\n"
    "        save_total_limit=1,                # mantém só o último checkpoint\n"
    "        load_best_model_at_end=False,\n"
    "        logging_steps=200,\n"
    "        seed=SEED,\n"
    "        report_to='none',\n"
    "        fp16=torch.cuda.is_available(),    # mixed precision se GPU\n"
    "    )\n"
    "\n"
    "    trainer = Trainer(\n"
    "        model=model,\n"
    "        args=training_args,\n"
    "        train_dataset=train_ds,\n"
    "        eval_dataset=test_ds,\n"
    "        tokenizer=BERT_TOKENIZER,\n"
    "        data_collator=DataCollatorWithPadding(BERT_TOKENIZER),\n"
    "        compute_metrics=compute_metrics,\n"
    "    )\n"
    "\n"
    "    trainer.train()\n"
    "    final_metrics = trainer.evaluate()\n"
    "    elapsed = time.time() - t0\n"
    "\n"
    "    f1w = final_metrics['eval_f1_weighted']\n"
    "    f1m = final_metrics['eval_f1_macro']\n"
    "    acc = final_metrics['eval_accuracy']\n"
    "    print(f'  ✓ BERT | F1w={f1w:.2%}  F1macro={f1m:.2%}  Acc={acc:.2%}  ({elapsed/60:.1f}min)')\n"
    "\n"
    "    # Libera VRAM\n"
    "    del model, trainer\n"
    "    if torch.cuda.is_available(): torch.cuda.empty_cache()\n"
    "\n"
    "    return {'Visão': visao_nome, 'Modelo': 'BERT (Bertimbau)',\n"
    "            'Acurácia': acc, 'Precisão': final_metrics['eval_precision'],\n"
    "            'Recall': final_metrics['eval_recall'],\n"
    "            'F1-Score': f1w, 'F1-Macro': f1m, 'Tempo (s)': round(elapsed, 1)}\n"
))

# ============================================================
# Célula 12 — Markdown executar visões
# ============================================================
cells.append(nbf.v4.new_markdown_cell(
    "## 4. Executar todas as visões\n\n"
    "Salva resultados parciais em `resultados/metricas_avancado_movies_partial.csv` "
    "a cada visão concluída — se travar, você não perde tudo."
))

# ============================================================
# Célula 13 — Executar LSTM nas 5 visões
# ============================================================
cells.append(nbf.v4.new_code_cell(
    "# ============================================================\n"
    "# CÉLULA 13 — LSTM nas 5 visões\n"
    "# ============================================================\n"
    "resultados_avancados = []\n"
    "PARTIAL_CSV = os.path.join(RESULTADOS, 'metricas_avancado_movies_partial.csv')\n"
    "\n"
    "def salvar_parcial():\n"
    "    if resultados_avancados:\n"
    "        pd.DataFrame(resultados_avancados).to_csv(PARTIAL_CSV, index=False)\n"
    "        print(f'  💾 Parcial salvo: {PARTIAL_CSV}')\n"
    "\n"
    "# V1: Sintético → Sintético\n"
    "resultados_avancados.append(run_lstm_vision(\n"
    "    S_tr['frase_limpa'], S_tr['classe'], S_te['frase_limpa'], S_te['classe'],\n"
    "    'V1: Sintético → Sintético'))\n"
    "salvar_parcial()\n"
    "\n"
    "# V2: Real → Real (controlado)\n"
    "resultados_avancados.append(run_lstm_vision(\n"
    "    R_tr['frase_limpa'], R_tr['classe'], R_te['frase_limpa'], R_te['classe'],\n"
    "    'V2: Real → Real'))\n"
    "salvar_parcial()\n"
    "\n"
    "# V3: Sintético → Real (controlado, mesmo test set do V2)\n"
    "resultados_avancados.append(run_lstm_vision(\n"
    "    S_tr['frase_limpa'], S_tr['classe'], R_te['frase_limpa'], R_te['classe'],\n"
    "    'V3: Sintético → Real'))\n"
    "salvar_parcial()\n"
    "\n"
    "# V4: Real → Real (desbalanceado)\n"
    "resultados_avancados.append(run_lstm_vision(\n"
    "    RD_tr['frase_limpa'], RD_tr['classe'], RD_te['frase_limpa'], RD_te['classe'],\n"
    "    'V4: Real → Real (desbalanceado)'))\n"
    "salvar_parcial()\n"
    "\n"
    "# V5: Sintético → Real (desbalanceado, mesmo test set do V4)\n"
    "resultados_avancados.append(run_lstm_vision(\n"
    "    S_tr['frase_limpa'], S_tr['classe'], RD_te['frase_limpa'], RD_te['classe'],\n"
    "    'V5: Sintético → Real (desbalanceado)'))\n"
    "salvar_parcial()\n"
))

# ============================================================
# Célula 14 — Executar BERT nas 5 visões
# ============================================================
cells.append(nbf.v4.new_code_cell(
    "# ============================================================\n"
    "# CÉLULA 14 — BERT nas 5 visões\n"
    "# ⚠️ ATENÇÃO: V4 (1.2M frases) levará ~6-9 horas na RTX 3070\n"
    "# ============================================================\n"
    "# V1\n"
    "resultados_avancados.append(run_bert_vision(\n"
    "    S_tr['frase_limpa'], S_tr['classe'], S_te['frase_limpa'], S_te['classe'],\n"
    "    'V1: Sintético → Sintético'))\n"
    "salvar_parcial()\n"
    "\n"
    "# V2\n"
    "resultados_avancados.append(run_bert_vision(\n"
    "    R_tr['frase_limpa'], R_tr['classe'], R_te['frase_limpa'], R_te['classe'],\n"
    "    'V2: Real → Real'))\n"
    "salvar_parcial()\n"
    "\n"
    "# V3\n"
    "resultados_avancados.append(run_bert_vision(\n"
    "    S_tr['frase_limpa'], S_tr['classe'], R_te['frase_limpa'], R_te['classe'],\n"
    "    'V3: Sintético → Real'))\n"
    "salvar_parcial()\n"
    "\n"
    "# V4 — DEMORA MUITO\n"
    "print('\\n⚠️ INICIANDO V4 com BERT — duração estimada 6-9h na RTX 3070')\n"
    "resultados_avancados.append(run_bert_vision(\n"
    "    RD_tr['frase_limpa'], RD_tr['classe'], RD_te['frase_limpa'], RD_te['classe'],\n"
    "    'V4: Real → Real (desbalanceado)'))\n"
    "salvar_parcial()\n"
    "\n"
    "# V5\n"
    "resultados_avancados.append(run_bert_vision(\n"
    "    S_tr['frase_limpa'], S_tr['classe'], RD_te['frase_limpa'], RD_te['classe'],\n"
    "    'V5: Sintético → Real (desbalanceado)'))\n"
    "salvar_parcial()\n"
))

# ============================================================
# Célula 15 — Markdown resultado final
# ============================================================
cells.append(nbf.v4.new_markdown_cell(
    "## 5. Resultado final — consolidar com clássicos do notebook 03\n\n"
    "Lê `resultados/metricas_5_visoes_movies.csv` (gerado pelo notebook 03), "
    "concatena com LSTM/BERT e gera tabela + gráfico **5 visões × 5 modelos × 5 métricas**."
))

# ============================================================
# Célula 16 — Consolidação + gráficos
# ============================================================
cells.append(nbf.v4.new_code_cell(
    "# ============================================================\n"
    "# CÉLULA 16 — Tabela final + gráficos comparativos\n"
    "# ============================================================\n"
    "import matplotlib.pyplot as plt\n"
    "\n"
    "df_avancado = pd.DataFrame(resultados_avancados)\n"
    "\n"
    "# Tenta carregar resultados clássicos do notebook 03\n"
    "csv_classicos = os.path.join(RESULTADOS, 'metricas_5_visoes_movies.csv')\n"
    "if os.path.exists(csv_classicos):\n"
    "    df_classicos = pd.read_csv(csv_classicos)\n"
    "    if 'F1-Macro' not in df_classicos.columns:\n"
    "        df_classicos['F1-Macro'] = df_classicos['F1-Score']  # fallback antigo\n"
    "    df_classicos['Tempo (s)'] = None\n"
    "    df_consolidado = pd.concat([df_classicos, df_avancado], ignore_index=True)\n"
    "    print(f'Consolidado: {len(df_classicos)} clássicos + {len(df_avancado)} avançados = {len(df_consolidado)} linhas')\n"
    "else:\n"
    "    df_consolidado = df_avancado.copy()\n"
    "    print('AVISO: arquivo de clássicos não encontrado. Apenas LSTM/BERT.')\n"
    "\n"
    "ordem_visoes = ['V1: Sintético → Sintético', 'V2: Real → Real', 'V3: Sintético → Real',\n"
    "                'V4: Real → Real (desbalanceado)', 'V5: Sintético → Real (desbalanceado)']\n"
    "ordem_modelos = ['Naive Bayes', 'Regressão Logística', 'SVM Linear', 'LSTM', 'BERT (Bertimbau)']\n"
    "df_consolidado['Visão'] = pd.Categorical(df_consolidado['Visão'], categories=ordem_visoes, ordered=True)\n"
    "df_consolidado['Modelo'] = pd.Categorical(df_consolidado['Modelo'], categories=ordem_modelos, ordered=True)\n"
    "df_consolidado = df_consolidado.sort_values(['Visão', 'Modelo']).reset_index(drop=True)\n"
    "\n"
    "# Tabela final F1 weighted e F1 macro\n"
    "for met in ['F1-Score', 'F1-Macro']:\n"
    "    pivot = df_consolidado.pivot(index='Visão', columns='Modelo', values=met)[ordem_modelos]\n"
    "    print(f'\\n=== {met} (× 100) ===')\n"
    "    print((pivot * 100).round(2).to_string())\n"
    "\n"
    "# Salva CSVs\n"
    "df_avancado.round(4).to_csv(os.path.join(RESULTADOS, 'metricas_avancado_movies.csv'), index=False)\n"
    "df_consolidado.round(4).to_csv(os.path.join(RESULTADOS, 'metricas_consolidado_movies.csv'), index=False)\n"
    "print(f'\\n✓ Salvo: resultados/metricas_avancado_movies.csv e metricas_consolidado_movies.csv')\n"
    "\n"
    "# Gráfico principal: F1 weighted, 5 visões × 5 modelos\n"
    "pivot_f1 = df_consolidado.pivot(index='Visão', columns='Modelo', values='F1-Score')[ordem_modelos]\n"
    "fig, ax = plt.subplots(figsize=(15, 7))\n"
    "pivot_f1.plot(kind='bar', ax=ax, rot=15, edgecolor='black', width=0.85)\n"
    "ax.set_ylabel('F1-Score (weighted)', fontsize=12)\n"
    "ax.set_title('Comparativo Clássicos vs Avançados — 5 Visões — Movies', fontsize=13, fontweight='bold')\n"
    "ax.set_ylim(0, 1.0)\n"
    "ax.legend(title='Modelo', loc='upper right', fontsize=9)\n"
    "ax.grid(axis='y', alpha=0.3)\n"
    "for container in ax.containers:\n"
    "    ax.bar_label(container, fmt='%.2f', padding=2, fontsize=7)\n"
    "plt.tight_layout()\n"
    "plt.savefig(os.path.join(RESULTADOS, 'grafico_consolidado_movies_f1weighted.png'), dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "\n"
    "# Gráfico F1 macro\n"
    "pivot_fm = df_consolidado.pivot(index='Visão', columns='Modelo', values='F1-Macro')[ordem_modelos]\n"
    "fig, ax = plt.subplots(figsize=(15, 7))\n"
    "pivot_fm.plot(kind='bar', ax=ax, rot=15, edgecolor='black', width=0.85)\n"
    "ax.set_ylabel('F1-Score (macro)', fontsize=12)\n"
    "ax.set_title('F1 Macro — Clássicos vs Avançados — 5 Visões — Movies', fontsize=13, fontweight='bold')\n"
    "ax.set_ylim(0, 1.0)\n"
    "ax.legend(title='Modelo', loc='upper right', fontsize=9)\n"
    "ax.grid(axis='y', alpha=0.3)\n"
    "for container in ax.containers:\n"
    "    ax.bar_label(container, fmt='%.2f', padding=2, fontsize=7)\n"
    "plt.tight_layout()\n"
    "plt.savefig(os.path.join(RESULTADOS, 'grafico_consolidado_movies_f1macro.png'), dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "\n"
    "print('\\n✓ Gráficos salvos: grafico_consolidado_movies_f1weighted.png + grafico_consolidado_movies_f1macro.png')\n"
))

# Monta notebook
nb.cells = cells
out_path = os.path.join(os.path.dirname(__file__), '04_movies_avancado.ipynb')
with io.open(out_path, 'w', encoding='utf-8') as f:
    nbf.write(nb, f)

print(f'Notebook criado: {out_path}')
print(f'Total de células: {len(nb.cells)}')
