# -*- coding: utf-8 -*-
"""Restaura imports completos do setup dos notebooks 01 e 02 (perdidos na padronização anterior)."""
import nbformat as nbf
import io

# === Notebook 01: célula 0 = setup ===
SETUP_01 = (
    "# ============================================================\n"
    "# CÉLULA DE SETUP — padrão (igual aos notebooks 03 e 04)\n"
    "# ============================================================\n"
    "# Notebooks 01 e 02 usam SOMENTE dados sintéticos (dados/processado/synthetic_dataset.csv)\n"
    "# Por isso o setup aqui é mais leve que o do notebook 03 (sem kagglehub).\n"
    "import os, sys, glob, re, warnings\n"
    "import numpy as np\n"
    "import pandas as pd\n"
    "import matplotlib.pyplot as plt\n"
    "import seaborn as sns\n"
    "\n"
    "from sklearn.model_selection import train_test_split, cross_val_score, learning_curve\n"
    "from sklearn.feature_extraction.text import TfidfVectorizer\n"
    "from sklearn.linear_model import LogisticRegression\n"
    "from sklearn.naive_bayes import MultinomialNB\n"
    "from sklearn.svm import LinearSVC\n"
    "from sklearn.metrics import (\n"
    "    classification_report,\n"
    "    confusion_matrix,\n"
    "    accuracy_score,\n"
    "    precision_recall_fscore_support,\n"
    ")\n"
    "from sklearn.pipeline import Pipeline\n"
    "\n"
    "sns.set_style('whitegrid')\n"
    "warnings.filterwarnings('ignore')\n"
    "\n"
    "# Reprodutibilidade\n"
    "SEED = 42\n"
    "np.random.seed(SEED)\n"
    "\n"
    "# Detecção de ambiente\n"
    "IN_COLAB = 'google.colab' in sys.modules\n"
    "\n"
    "if IN_COLAB:\n"
    "    if not os.path.exists('/content/tcc-analise-sentimento'):\n"
    "        os.system('git clone https://github.com/ROMAUSKI/tcc-analise-sentimento.git /content/tcc-analise-sentimento')\n"
    "    else:\n"
    "        os.system('cd /content/tcc-analise-sentimento && git pull')\n"
    "    BASE_DIR = '/content/tcc-analise-sentimento'\n"
    "else:\n"
    "    BASE_DIR = os.path.abspath(os.path.join(os.getcwd(), '..'))\n"
    "\n"
    "# Caminhos do projeto (consistentes em todos os notebooks)\n"
    "DADOS_BRUTOS_MOVIES = os.path.join(BASE_DIR, 'dados', 'brutos')\n"
    "DADOS_BRUTOS_APPS   = os.path.join(BASE_DIR, 'dados', 'brutos_apps')\n"
    "DADOS_PROCESSADO    = os.path.join(BASE_DIR, 'dados', 'processado')\n"
    "RESULTADOS          = os.path.join(BASE_DIR, 'resultados')\n"
    "os.makedirs(RESULTADOS, exist_ok=True)\n"
    "\n"
    "print(f'Ambiente: {\"Colab\" if IN_COLAB else \"Local\"}')\n"
    "print(f'BASE_DIR: {BASE_DIR}')\n"
    "print('Setup pronto.')\n"
)

# === Notebook 02: célula 1 = setup (carrega df também) ===
SETUP_02 = (
    "# ============================================================\n"
    "# CÉLULA DE SETUP — padrão + carregamento do dataset sintético\n"
    "# ============================================================\n"
    "import os, sys, re, warnings\n"
    "import numpy as np\n"
    "import pandas as pd\n"
    "import matplotlib.pyplot as plt\n"
    "import seaborn as sns\n"
    "\n"
    "from sklearn.model_selection import train_test_split, cross_val_score, learning_curve\n"
    "from sklearn.feature_extraction.text import TfidfVectorizer\n"
    "from sklearn.linear_model import LogisticRegression\n"
    "from sklearn.naive_bayes import MultinomialNB\n"
    "from sklearn.svm import LinearSVC\n"
    "from sklearn.metrics import (\n"
    "    classification_report,\n"
    "    confusion_matrix,\n"
    "    accuracy_score,\n"
    "    precision_recall_fscore_support,\n"
    ")\n"
    "from sklearn.pipeline import Pipeline\n"
    "\n"
    "sns.set_style('whitegrid')\n"
    "warnings.filterwarnings('ignore')\n"
    "\n"
    "# Reprodutibilidade\n"
    "SEED = 42\n"
    "np.random.seed(SEED)\n"
    "\n"
    "# Detecção de ambiente\n"
    "IN_COLAB = 'google.colab' in sys.modules\n"
    "\n"
    "if IN_COLAB:\n"
    "    if not os.path.exists('/content/tcc-analise-sentimento'):\n"
    "        os.system('git clone https://github.com/ROMAUSKI/tcc-analise-sentimento.git /content/tcc-analise-sentimento')\n"
    "    else:\n"
    "        os.system('cd /content/tcc-analise-sentimento && git pull')\n"
    "    BASE_DIR = '/content/tcc-analise-sentimento'\n"
    "else:\n"
    "    BASE_DIR = os.path.abspath(os.path.join(os.getcwd(), '..'))\n"
    "\n"
    "# Caminhos do projeto\n"
    "DADOS_BRUTOS_MOVIES = os.path.join(BASE_DIR, 'dados', 'brutos')\n"
    "DADOS_BRUTOS_APPS   = os.path.join(BASE_DIR, 'dados', 'brutos_apps')\n"
    "DADOS_PROCESSADO    = os.path.join(BASE_DIR, 'dados', 'processado')\n"
    "RESULTADOS          = os.path.join(BASE_DIR, 'resultados')\n"
    "os.makedirs(RESULTADOS, exist_ok=True)\n"
    "\n"
    "# Alias para compatibilidade com células existentes do notebook 02\n"
    "dir_resultados = RESULTADOS\n"
    "\n"
    "# Carrega o dataset sintético processado (gerado pelo notebook 01)\n"
    "caminho_csv = os.path.join(DADOS_PROCESSADO, 'synthetic_dataset.csv')\n"
    "df = pd.read_csv(caminho_csv)\n"
    "df = df.dropna(subset=['frase_limpa'])\n"
    "X = df['frase_limpa']\n"
    "y = df['classe']\n"
    "\n"
    "print(f'Ambiente: {\"Colab\" if IN_COLAB else \"Local\"}')\n"
    "print(f'BASE_DIR: {BASE_DIR}')\n"
    "print(f'Dataset carregado: {len(df)} amostras')\n"
    "print(y.value_counts())\n"
)

# Aplicar
for nb_path, idx, novo_setup in [
    ('src/01_movies_training.ipynb', 0, SETUP_01),
    ('src/02_movies_robustness.ipynb', 1, SETUP_02),
]:
    with io.open(nb_path, 'r', encoding='utf-8') as f:
        nb = nbf.read(f, as_version=4)
    nb.cells[idx].source = novo_setup
    with io.open(nb_path, 'w', encoding='utf-8') as f:
        nbf.write(nb, f)
    print(f'OK: {nb_path} — célula {idx} restaurada com todos os imports')
