# -*- coding: utf-8 -*-
"""Refatora a célula 1 do notebook 04 — auto-instalação Colab + detecção/instruções local."""
import nbformat as nbf
import io

nb_path = 'src/04_movies_avancado.ipynb'
with io.open(nb_path, 'r', encoding='utf-8') as f:
    nb = nbf.read(f, as_version=4)

# Atualiza célula 0 (markdown overview) para refletir auto-install
nb.cells[0].source = (
    "# Notebook 04 — Modelos Avançados (LSTM + BERT/Bertimbau) · Movies\n\n"
    "Replica as **5 visões** do notebook 03 com modelos de **deep learning**:\n\n"
    "- **LSTM** (PyTorch) — embeddings aprendidos do zero\n"
    "- **BERT (Bertimbau base)** — `neuralmind/bert-base-portuguese-cased`, fine-tuning\n\n"
    "Objetivo: contrastar **técnicas básicas** (NB/LR/SVM do notebook 03) com **técnicas avançadas** "
    "para mostrar se o reality gap (V3/V5) persiste com modelos contextuais.\n\n"
    "## ✨ Auto-setup\n\n"
    "A **Célula 1** detecta o ambiente e cuida das dependências automaticamente:\n"
    "- **No Colab:** instala silenciosamente `transformers`, `accelerate`, `kagglehub` (PyTorch+CUDA já vem pronto)\n"
    "- **Local:** verifica se PyTorch tem CUDA habilitado e mostra o comando de instalação se faltar\n\n"
    "## ⏱️ Tempo esperado (RTX 3070, 8GB VRAM, dataset real completo ~1.5M)\n\n"
    "| Etapa | Tempo |\n"
    "|---|---|\n"
    "| LSTM em V1/V2/V3/V5 (visões pequenas) | ~5 min total |\n"
    "| LSTM em V4 (1.2M frases) | ~30-60 min |\n"
    "| BERT em V1/V2/V3/V5 (visões pequenas) | ~10 min total |\n"
    "| BERT em V4 (1.2M frases, 3 epochs) | **~6-9 HORAS** ⚠️ |\n"
    "| **Total (rodando overnight)** | **~7-10 horas** |\n\n"
    "Para teste rápido, ajuste `MAX_SAMPLES_REAL = 100_000` na **Célula 3**."
)

# Reescreve célula 1 — auto-setup completo (detecção + instalação)
nb.cells[1].source = (
    "# ============================================================\n"
    "# CÉLULA 1 — AUTO-SETUP DO AMBIENTE\n"
    "# Detecta Colab vs Local e instala/verifica dependências\n"
    "# ============================================================\n"
    "import sys, subprocess, importlib\n"
    "\n"
    "IN_COLAB = 'google.colab' in sys.modules\n"
    "print(f'Ambiente detectado: {\"Google Colab\" if IN_COLAB else \"Local\"}')\n"
    "\n"
    "def _pip_install(pkgs, quiet=True):\n"
    "    \"\"\"Instala via pip dentro do mesmo Python que está rodando o notebook.\"\"\"\n"
    "    cmd = [sys.executable, '-m', 'pip', 'install'] + (['-q'] if quiet else []) + pkgs\n"
    "    subprocess.run(cmd, check=True)\n"
    "\n"
    "def _check_module(name):\n"
    "    \"\"\"Retorna True se o módulo importa.\"\"\"\n"
    "    try:\n"
    "        importlib.import_module(name)\n"
    "        return True\n"
    "    except ImportError:\n"
    "        return False\n"
    "\n"
    "# ============================================================\n"
    "# CASO 1 — Google Colab\n"
    "# ============================================================\n"
    "if IN_COLAB:\n"
    "    print('Instalando dependências no Colab (silencioso)...')\n"
    "    pkgs_a_instalar = []\n"
    "    if not _check_module('transformers'): pkgs_a_instalar.append('transformers>=4.40')\n"
    "    if not _check_module('accelerate'):   pkgs_a_instalar.append('accelerate>=0.30')\n"
    "    if not _check_module('kagglehub'):    pkgs_a_instalar.append('kagglehub>=1.0.1')\n"
    "    if pkgs_a_instalar:\n"
    "        _pip_install(pkgs_a_instalar)\n"
    "        print(f'  Instalados: {pkgs_a_instalar}')\n"
    "    else:\n"
    "        print('  Todas as dependências Colab já presentes.')\n"
    "    print('Colab traz PyTorch + CUDA pré-instalados — sem ação necessária para GPU.')\n"
    "\n"
    "# ============================================================\n"
    "# CASO 2 — Local (Windows/Linux/Mac com hardware do usuário)\n"
    "# ============================================================\n"
    "else:\n"
    "    falta_torch = not _check_module('torch')\n"
    "    falta_tx    = not _check_module('transformers')\n"
    "    falta_acc   = not _check_module('accelerate')\n"
    "    falta_kh    = not _check_module('kagglehub')\n"
    "\n"
    "    # Pacotes não-torch são fáceis: instala direto\n"
    "    pkgs_simples = []\n"
    "    if falta_tx:  pkgs_simples.append('transformers>=4.40')\n"
    "    if falta_acc: pkgs_simples.append('accelerate>=0.30')\n"
    "    if falta_kh:  pkgs_simples.append('kagglehub>=1.0.1')\n"
    "    if pkgs_simples:\n"
    "        print(f'Instalando localmente: {pkgs_simples}')\n"
    "        _pip_install(pkgs_simples, quiet=False)\n"
    "\n"
    "    # PyTorch precisa de cuidado: usuário deve escolher CUDA vs CPU\n"
    "    if falta_torch:\n"
    "        print('\\n' + '='*70)\n"
    "        print('❌ PyTorch NÃO está instalado. Instale ANTES de prosseguir:')\n"
    "        print('='*70)\n"
    "        print('\\nPara GPU NVIDIA (RTX 3000+, recomendado para BERT):')\n"
    "        print('   pip install torch --index-url https://download.pytorch.org/whl/cu121')\n"
    "        print('\\nPara CPU apenas (BERT vai levar DIAS — só use se não tem GPU):')\n"
    "        print('   pip install torch')\n"
    "        print('\\nDepois reinicie o kernel do notebook e execute esta célula novamente.')\n"
    "        print('='*70)\n"
    "        raise SystemExit('Instale PyTorch e reinicie o kernel.')\n"
    "\n"
    "# ============================================================\n"
    "# Verificação final: PyTorch + CUDA\n"
    "# ============================================================\n"
    "import torch\n"
    "print(f'\\nPyTorch versão: {torch.__version__}')\n"
    "if torch.cuda.is_available():\n"
    "    gpu_name = torch.cuda.get_device_name(0)\n"
    "    gpu_vram = torch.cuda.get_device_properties(0).total_memory / 1e9\n"
    "    print(f'✅ CUDA disponível — GPU: {gpu_name} ({gpu_vram:.1f} GB VRAM)')\n"
    "else:\n"
    "    print('⚠️ CUDA NÃO disponível — vai rodar em CPU.')\n"
    "    if not IN_COLAB:\n"
    "        print('   Para habilitar GPU localmente, REINSTALE o PyTorch com:')\n"
    "        print('   pip install torch --index-url https://download.pytorch.org/whl/cu121 --upgrade')\n"
    "        print('   E reinicie o kernel do notebook.')\n"
    "    print('   Treinar BERT em CPU é INVIÁVEL (semanas). Use Colab com runtime GPU se necessário.')\n"
)

# Insere uma nova célula 2 com setup de paths e device (separada da instalação)
cell_paths = nbf.v4.new_code_cell(
    "# ============================================================\n"
    "# CÉLULA 2 — Imports principais + paths + reprodutibilidade\n"
    "# ============================================================\n"
    "import os, shutil, re, time, json\n"
    "import numpy as np\n"
    "import pandas as pd\n"
    "import torch\n"
    "\n"
    "# Reprodutibilidade\n"
    "SEED = 42\n"
    "np.random.seed(SEED)\n"
    "torch.manual_seed(SEED)\n"
    "if torch.cuda.is_available():\n"
    "    torch.cuda.manual_seed_all(SEED)\n"
    "\n"
    "# Paths (Colab clona o repo, local usa estrutura existente)\n"
    "if IN_COLAB:\n"
    "    if not os.path.exists('/content/tcc-analise-sentimento'):\n"
    "        os.system('git clone https://github.com/ROMAUSKI/tcc-analise-sentimento.git /content/tcc-analise-sentimento')\n"
    "    else:\n"
    "        os.system('cd /content/tcc-analise-sentimento && git pull')\n"
    "    BASE_DIR = '/content/tcc-analise-sentimento'\n"
    "    REAL_DATA_PATH = '/content/sample_data/dataset_real_sentimentos'\n"
    "else:\n"
    "    BASE_DIR = os.path.abspath(os.path.join(os.getcwd(), '..'))\n"
    "    REAL_DATA_PATH = os.path.join(BASE_DIR, 'src', 'dados_reais')\n"
    "\n"
    "# Dataset real via kagglehub se ainda não existir\n"
    "if not os.path.exists(REAL_DATA_PATH) or not os.listdir(REAL_DATA_PATH):\n"
    "    import kagglehub\n"
    "    print('Baixando dataset real do Kaggle (~877 MB, só na 1ª vez)...')\n"
    "    cache_path = kagglehub.dataset_download('fredericods/ptbr-sentiment-analysis-datasets')\n"
    "    os.makedirs(REAL_DATA_PATH, exist_ok=True)\n"
    "    for f in os.listdir(cache_path):\n"
    "        shutil.copy(os.path.join(cache_path, f), os.path.join(REAL_DATA_PATH, f))\n"
    "    print(f'Dataset real disponível em: {REAL_DATA_PATH}')\n"
    "else:\n"
    "    print(f'Dataset real já existe em: {REAL_DATA_PATH}')\n"
    "\n"
    "DADOS_BRUTOS_MOVIES = os.path.join(BASE_DIR, 'dados', 'brutos')\n"
    "DADOS_BRUTOS_APPS   = os.path.join(BASE_DIR, 'dados', 'brutos_apps')\n"
    "DADOS_PROCESSADO    = os.path.join(BASE_DIR, 'dados', 'processado')\n"
    "RESULTADOS          = os.path.join(BASE_DIR, 'resultados')\n"
    "CHECKPOINTS         = os.path.join(BASE_DIR, 'src', 'checkpoints_avancado')\n"
    "os.makedirs(CHECKPOINTS, exist_ok=True)\n"
    "\n"
    "DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n"
    "print(f'\\nBASE_DIR: {BASE_DIR}')\n"
    "print(f'DEVICE:   {DEVICE}')\n"
)

# Insere essa nova célula APÓS a célula 1 (auto-setup)
nb.cells.insert(2, cell_paths)

with io.open(nb_path, 'w', encoding='utf-8') as f:
    nbf.write(nb, f)

print(f'Notebook atualizado. Total: {len(nb.cells)} células')
