# -*- coding: utf-8 -*-
"""Refatora a Célula 1 do notebook 04 para auto-instalar PyTorch com CUDA sem precisar reiniciar kernel."""
import nbformat as nbf
import io

nb_path = 'src/04_movies_avancado.ipynb'
with io.open(nb_path, 'r', encoding='utf-8') as f:
    nb = nbf.read(f, as_version=4)

# Reescreve célula 1 — auto-setup completo com auto-instalação CUDA
nb.cells[1].source = (
    "# ============================================================\n"
    "# CÉLULA 1 — AUTO-SETUP DO AMBIENTE (auto-instala tudo, inclusive PyTorch+CUDA)\n"
    "# ============================================================\n"
    "import sys, subprocess, importlib\n"
    "\n"
    "IN_COLAB = 'google.colab' in sys.modules\n"
    "print(f'Ambiente detectado: {\"Google Colab\" if IN_COLAB else \"Local\"}')\n"
    "\n"
    "# Configurações\n"
    "CUDA_VERSION = 'cu121'   # cu121 cobre RTX 3000+ e drivers modernos. Use 'cu118' para drivers antigos.\n"
    "AUTO_INSTALL_PYTORCH_CUDA = True  # se False, só avisa em vez de instalar\n"
    "\n"
    "def _run(cmd, check=True, quiet=False):\n"
    "    \"\"\"Executa comando shell e mostra output (a menos que quiet).\"\"\"\n"
    "    if quiet:\n"
    "        return subprocess.run(cmd, check=check, capture_output=True, text=True)\n"
    "    return subprocess.run(cmd, check=check)\n"
    "\n"
    "def _module_existe(name):\n"
    "    \"\"\"Verifica se módulo está instalado SEM importá-lo (importlib.util).\"\"\"\n"
    "    return importlib.util.find_spec(name) is not None\n"
    "\n"
    "def _torch_tem_cuda():\n"
    "    \"\"\"Roda torch.cuda.is_available() em SUBPROCESSO Python isolado.\n"
    "    Assim NÃO carrega torch no kernel atual — permitindo reinstalar sem reiniciar.\"\"\"\n"
    "    if not _module_existe('torch'):\n"
    "        return None  # nem instalado\n"
    "    try:\n"
    "        r = subprocess.run(\n"
    "            [sys.executable, '-c', 'import torch; print(torch.cuda.is_available())'],\n"
    "            capture_output=True, text=True, timeout=60\n"
    "        )\n"
    "        return r.stdout.strip() == 'True'\n"
    "    except Exception:\n"
    "        return False\n"
    "\n"
    "# ============================================================\n"
    "# 1) DEPENDÊNCIAS NÃO-PESADAS (transformers, accelerate, kagglehub, tqdm)\n"
    "# ============================================================\n"
    "pkgs_simples = []\n"
    "for pkg, name in [('transformers>=4.40', 'transformers'),\n"
    "                  ('accelerate>=0.30', 'accelerate'),\n"
    "                  ('kagglehub>=1.0.1', 'kagglehub'),\n"
    "                  ('tqdm>=4.65', 'tqdm')]:\n"
    "    if not _module_existe(name):\n"
    "        pkgs_simples.append(pkg)\n"
    "\n"
    "if pkgs_simples:\n"
    "    print(f'\\nInstalando dependências leves: {pkgs_simples}')\n"
    "    _run([sys.executable, '-m', 'pip', 'install', '-q'] + pkgs_simples)\n"
    "else:\n"
    "    print('Dependências leves já presentes (transformers, accelerate, kagglehub, tqdm).')\n"
    "\n"
    "# ============================================================\n"
    "# 2) PYTORCH COM CUDA (o pulo do gato)\n"
    "# ============================================================\n"
    "if IN_COLAB:\n"
    "    print('\\nColab: PyTorch + CUDA já vêm pré-instalados, sem ação necessária.')\n"
    "else:\n"
    "    estado = _torch_tem_cuda()  # None=não instalado, False=CPU-only, True=CUDA OK\n"
    "    if estado is True:\n"
    "        print('\\n✅ PyTorch com CUDA já instalado e funcionando.')\n"
    "    else:\n"
    "        if estado is None:\n"
    "            motivo = 'PyTorch NÃO está instalado'\n"
    "        else:\n"
    "            motivo = 'PyTorch instalado SEM CUDA (versão CPU-only)'\n"
    "        print(f'\\n⚠️ {motivo}.')\n"
    "\n"
    "        # IMPORTANTE: torch NÃO foi importado neste kernel ainda (estamos usando subprocess para checar).\n"
    "        # Por isso podemos reinstalar via pip SEM precisar reiniciar — o import futuro pega a versão nova.\n"
    "        if 'torch' in sys.modules:\n"
    "            print('\\n❌ torch já foi importado neste kernel — reinicie o kernel e rode esta célula primeiro.')\n"
    "            raise SystemExit('Reinicie o kernel manualmente.')\n"
    "\n"
    "        if not AUTO_INSTALL_PYTORCH_CUDA:\n"
    "            print(f'   Auto-instalação desativada. Instale manualmente:')\n"
    "            print(f'   pip install torch --index-url https://download.pytorch.org/whl/{CUDA_VERSION} --upgrade --force-reinstall')\n"
    "            raise SystemExit('Defina AUTO_INSTALL_PYTORCH_CUDA = True ou instale manualmente.')\n"
    "\n"
    "        print(f'\\n📦 Instalando PyTorch com CUDA ({CUDA_VERSION}) — pode demorar alguns minutos (~2.5 GB)...')\n"
    "        cmd = [sys.executable, '-m', 'pip', 'install', '--upgrade',\n"
    "               '--force-reinstall' if estado is False else '--no-deps',\n"
    "               'torch',\n"
    "               '--index-url', f'https://download.pytorch.org/whl/{CUDA_VERSION}']\n"
    "        # Para reinstalação CPU->CUDA, usa --force-reinstall. Para instalação fresh, sem deps extras.\n"
    "        if estado is None:\n"
    "            cmd = [sys.executable, '-m', 'pip', 'install', 'torch',\n"
    "                   '--index-url', f'https://download.pytorch.org/whl/{CUDA_VERSION}']\n"
    "        _run(cmd)\n"
    "\n"
    "        # Verifica novamente em subprocesso\n"
    "        if _torch_tem_cuda():\n"
    "            print('\\n✅ PyTorch com CUDA instalado com sucesso!')\n"
    "        else:\n"
    "            print('\\n❌ Instalação não habilitou CUDA. Verifique driver NVIDIA e tente cu118 em vez de cu121.')\n"
    "            print('   Comando manual: pip install torch --index-url https://download.pytorch.org/whl/cu118 --upgrade --force-reinstall')\n"
    "            raise SystemExit('Falha em habilitar CUDA.')\n"
    "\n"
    "# ============================================================\n"
    "# 3) AGORA SIM, importa torch (carrega versão nova se foi reinstalada)\n"
    "# ============================================================\n"
    "import torch\n"
    "print(f'\\nPyTorch versão: {torch.__version__}')\n"
    "if torch.cuda.is_available():\n"
    "    gpu_name = torch.cuda.get_device_name(0)\n"
    "    gpu_vram = torch.cuda.get_device_properties(0).total_memory / 1e9\n"
    "    print(f'✅ CUDA OK — GPU: {gpu_name} ({gpu_vram:.1f} GB VRAM)')\n"
    "else:\n"
    "    print('⚠️ Sem CUDA — vai rodar em CPU (BERT inviável). Use Colab GPU se necessário.')\n"
)

with io.open(nb_path, 'w', encoding='utf-8') as f:
    nbf.write(nb, f)

print(f'Notebook atualizado. Total: {len(nb.cells)} células')
