# -*- coding: utf-8 -*-
"""Salva as frases NEUTRAS de Apps geradas pelo Claude Sonnet 4.6 adaptativo."""
import os, io

RAW = '''"Aplicativos móveis são programas instalados em dispositivos como smartphones e tablets."
"A App Store da Apple foi lançada em julho de 2008."
"A Google Play Store disponibiliza aplicativos para dispositivos Android."
"Aplicativos podem ser gratuitos, pagos ou baseados em assinaturas."
"O modelo freemium oferece funções básicas gratuitas e recursos avançados pagos."
"Aplicativos nativos são desenvolvidos especificamente para um sistema operacional."
"Aplicativos híbridos funcionam em múltiplas plataformas usando uma única base de código."
"O Flutter é um framework desenvolvido pelo Google para criação de apps multiplataforma."
"React Native permite desenvolver aplicativos usando JavaScript."
"Aplicativos precisam ser atualizados para corrigir falhas de segurança."
"Notificações push são mensagens enviadas pelo aplicativo ao dispositivo do usuário."
"Aplicativos consomem memória RAM do dispositivo durante sua execução."
"O tamanho de um aplicativo é medido em megabytes ou gigabytes."
"Aplicativos de streaming exigem conexão constante com a internet."
"Alguns aplicativos funcionam no modo offline após o download inicial de dados."
"Permissões de aplicativos determinam quais recursos do dispositivo podem ser acessados."
"Aplicativos de redes sociais permitem compartilhamento de conteúdo entre usuários."
"O WhatsApp foi adquirido pelo Facebook em 2014 por 19 bilhões de dólares."
"Aplicativos de banco permitem transferências, pagamentos e consultas de saldo."
"O Pix é um sistema de pagamento instantâneo integrado a vários aplicativos bancários."
"Aplicativos de saúde podem monitorar frequência cardíaca e passos dados."
"Aplicativos de GPS utilizam dados de satélite para determinar a localização do usuário."
"O Google Maps oferece rotas para carro, transporte público, bicicleta e a pé."
"Aplicativos de e-commerce permitem compras diretamente pelo smartphone."
"O Mercado Livre é uma plataforma de compras com aplicativo disponível no Brasil."
"Aplicativos educacionais oferecem cursos, quizzes e materiais de aprendizagem."
"O Duolingo é um aplicativo de ensino de idiomas com sistema de gamificação."
"Aplicativos de streaming de música permitem ouvir faixas sob demanda."
"O Spotify possui mais de 600 milhões de usuários ativos mensais."
"Aplicativos de vídeo curto exibem conteúdo em formato vertical."
"O TikTok registrou mais de 3 bilhões de downloads em todo o mundo."
"Aplicativos de delivery conectam restaurantes a consumidores finais."
"O iFood opera no Brasil, México, Colômbia e Portugal."
"Aplicativos de transporte utilizam geolocalização para conectar passageiros e motoristas."
"O Uber está presente em mais de 70 países."
"Aplicativos de produtividade incluem editores de texto, planilhas e gerenciadores de tarefas."
"O Google Docs permite edição colaborativa de documentos em tempo real."
"Aplicativos de câmera oferecem filtros, modos de exposição e edição de imagens."
"Aplicativos podem ser distribuídos fora das lojas oficiais em arquivos APK no Android."
"O processo de publicar um app na App Store exige aprovação da Apple."
"Aplicativos maliciosos podem roubar dados pessoais dos usuários."
"Sandboxing é uma técnica que isola aplicativos para proteger o sistema operacional."
"Aplicativos de jogos representam uma das categorias mais lucrativas das lojas digitais."
"O PUBG Mobile foi um dos jogos mobile mais baixados globalmente."
"Aplicativos de meditação guiam o usuário por exercícios de respiração e atenção plena."
"O Calm e o Headspace são exemplos de aplicativos de meditação."
"Aplicativos de clima utilizam dados meteorológicos para exibir previsões."
"A precisão das previsões depende da qualidade dos dados fornecidos pelos servidores."
"Aplicativos de agenda sincronizam compromissos com serviços de nuvem."
"O Google Calendar permite compartilhar calendários com outros usuários."
"Aplicativos de leitura oferecem acesso a livros digitais em formato ePub ou PDF."
"O Kindle é um aplicativo de leitura desenvolvido pela Amazon."
"Aplicativos de podcast permitem ouvir episódios sob demanda ou baixar para uso offline."
"O Spotify e o Apple Podcasts são plataformas populares de distribuição de podcasts."
"Aplicativos de videoconferência permitem reuniões com múltiplos participantes simultâneos."
"O Zoom suporta até mil participantes em um único webinar."
"Aplicativos de armazenamento em nuvem sincronizam arquivos entre dispositivos."
"O Google Drive oferece 15 GB de armazenamento gratuito por conta."
"Aplicativos de senha gerenciam e criptografam credenciais de acesso do usuário."
"O 1Password e o LastPass são exemplos de gerenciadores de senhas."
"Aplicativos de VPN criam túneis criptografados para a navegação do usuário."
"Aplicativos de antivírus escaneiam o dispositivo em busca de ameaças digitais."
"Aplicativos de acessibilidade incluem leitores de tela e ampliadores de texto."
"O TalkBack é o leitor de tela nativo do Android."
"Aplicativos de reconhecimento de voz convertem fala em texto."
"O Google Assistant e a Siri são assistentes de voz integrados a aplicativos."
"Aplicativos de tradução suportam dezenas de idiomas simultâneos."
"O Google Tradutor suporta mais de 130 idiomas."
"Aplicativos de escaneamento convertem documentos físicos em arquivos digitais."
"Aplicativos de assinatura digital permitem assinar documentos eletronicamente."
"O Autentique é um serviço brasileiro de assinatura eletrônica com aplicativo."
"Aplicativos de controle financeiro categorizam receitas e despesas automaticamente."
"O Mobills e o GuiaBolso são exemplos de aplicativos financeiros brasileiros."
"Aplicativos de criptomoedas exibem cotações e permitem transações em blockchain."
"O Binance é uma corretora de criptoativos com aplicativo móvel."
"Aplicativos de notícias agregam conteúdo de múltiplas fontes em um único feed."
"O Google Notícias organiza artigos com base nos interesses do usuário."
"Aplicativos de esportes exibem resultados, tabelas e estatísticas em tempo real."
"O Sofascore é um aplicativo de placar ao vivo popular no Brasil."
"Aplicativos de apostas esportivas requerem verificação de identidade para cadastro."
"Aplicativos de telemedicina permitem consultas médicas por videochamada."
"O aplicativo do SUS disponibiliza a carteira de vacinação digital no Brasil."
"Aplicativos de rastreamento de encomendas mostram o status de entrega em tempo real."
"Os Correios oferecem um aplicativo oficial para rastreamento de objetos postais."
"Aplicativos de mapa offline armazenam mapas localmente para uso sem internet."
"O Maps.me permite navegar sem conexão após o download do mapa da região."
"Aplicativos de controle parental limitam o tempo de uso e filtram conteúdo."
"O Google Family Link permite monitorar atividades em dispositivos infantis."
"Aplicativos de emergência podem acionar serviços de socorro com um único toque."
"O aplicativo Onde Estou! transmite localização em situações de emergência."
"Aplicativos de transporte público exibem horários e itinerários de ônibus e metrô."
"O Moovit oferece informações de transporte coletivo em mais de 3.500 cidades."
"Aplicativos de rideshare calculam tarifas com base em distância e tempo de viagem."
"Aplicativos de aluguel de bicicletas e patinetes utilizam QR codes para desbloqueio."
"Aplicativos de hotelaria permitem reservas e check-in online."
"O Booking.com e o Airbnb são plataformas de hospedagem com aplicativo móvel."
"Aplicativos de companhias aéreas exibem cartões de embarque digitais."
"A LATAM e a Gol possuem aplicativos com check-in online disponível."
"Aplicativos de idiomas utilizam reconhecimento de voz para avaliar pronúncia."
"O Babbel usa exercícios de conversação para ensino de idiomas."
"Aplicativos de culinária oferecem receitas com listas de ingredientes e modo de preparo."
"O Tastemade e o TudoGostoso são exemplos de aplicativos de receitas."
"Aplicativos de fitness registram treinos, séries e repetições realizadas."
"O Strava é um aplicativo de rastreamento de atividades físicas ao ar livre."
"Aplicativos de monitoramento de sono analisam padrões de descanso pelo microfone e acelerômetro."
"O Sleep Cycle usa sensores do smartphone para analisar o sono do usuário."
"Aplicativos de realidade aumentada sobrepõem elementos digitais ao ambiente real."
"O IKEA Place permite visualizar móveis virtuais no ambiente real pelo smartphone."
"Aplicativos de compras utilizam notificações para alertar sobre promoções e cupons."
"O Shopee opera no Brasil desde 2019 com aplicativo de marketplace."
"Aplicativos de marketplace conectam vendedores e compradores em uma única plataforma."
"Aplicativos de leilão permitem dar lances em tempo real pelo smartphone."
"O OLX é um aplicativo de anúncios classificados muito utilizado no Brasil."
"Aplicativos de imóveis exibem plantas, fotos e localização de propriedades à venda."
"O ZAP Imóveis e o Viva Real são plataformas imobiliárias com aplicativo."
"Aplicativos de emprego conectam candidatos a vagas abertas no mercado."
"O LinkedIn e o Indeed são plataformas de recrutamento com aplicativo móvel."
"Aplicativos de freelance permitem contratar profissionais para projetos pontuais."
"O Workana é uma plataforma de freelance popular na América Latina."
"Aplicativos de gerenciamento de projetos organizam tarefas, prazos e equipes."
"O Trello usa um sistema de quadros e cartões para organização de tarefas."
"Aplicativos de comunicação empresarial centralizam mensagens e arquivos em canais."
"O Slack permite criar canais temáticos para comunicação entre equipes."
"Aplicativos de assinatura de documentos registram data e IP do signatário."
"Aplicativos de escaneamento de código de barras identificam produtos pelo EAN."
"O Google Lens reconhece objetos, textos e plantas por meio da câmera."
"Aplicativos de reconhecimento musical identificam músicas pelo áudio captado."
"O Shazam pode identificar uma música em segundos a partir de um trecho."
"Aplicativos de rádio online transmitem estações ao vivo pela internet."
"O TuneIn agrega milhares de estações de rádio de todo o mundo."
"Aplicativos de e-mail sincronizam caixas de entrada com servidores remotos."
"O Gmail possui mais de 1,8 bilhão de usuários ativos globalmente."
"Aplicativos de calendário enviam lembretes antes de eventos agendados."
"Aplicativos de lista de tarefas permitem definir prioridades e datas limite."
"O Todoist e o Microsoft To Do são exemplos de aplicativos de tarefas."
"Aplicativos de notas suportam texto, imagens, áudios e checklists."
"O Notion permite criar bancos de dados, wikis e documentos colaborativos."
"Aplicativos de PDF permitem anotações, destaques e preenchimento de formulários."
"O Adobe Acrobat Reader está disponível para iOS e Android gratuitamente."
"Aplicativos de compressão de arquivos suportam formatos como ZIP e RAR."
"Aplicativos de compartilhamento de arquivos usam Wi-Fi direto ou Bluetooth."
"O SHAREit permite transferir arquivos entre dispositivos sem internet."
"Aplicativos de controle remoto permitem operar TVs e aparelhos via infravermelho."
"Aplicativos de smart home controlam lâmpadas, câmeras e termostatos inteligentes."
"O Google Home centraliza o controle de dispositivos compatíveis com Google Assistant."
"Aplicativos de monitoramento de câmeras exibem imagens ao vivo de câmeras IP."
"Aplicativos de segurança residencial enviam alertas de movimento em tempo real."
"O Ring possui câmeras e um aplicativo integrado para monitoramento residencial."
"Aplicativos de bate-papo por vídeo permitem chamadas individuais e em grupo."
"O Google Meet suporta reuniões com até 1.000 participantes em planos pagos."
"Aplicativos de armazenamento de fotos fazem backup automático da galeria."
"O Google Fotos oferece backup gratuito com compressão de imagens."
"Aplicativos de edição de fotos oferecem ferramentas de recorte, filtro e ajuste de cores."
"O Lightroom Mobile é um editor de fotos profissional para dispositivos móveis."
"Aplicativos de edição de vídeo permitem cortar, inserir trilha e adicionar legendas."
"O CapCut é um aplicativo de edição de vídeo popular entre criadores de conteúdo."
"Aplicativos de criação de artes gráficas oferecem templates e bibliotecas de ícones."
"O Canva permite criar posts, apresentações e materiais visuais pelo smartphone."
"Aplicativos de impressão enviam documentos para impressoras via Wi-Fi ou Bluetooth."
"O HP Smart conecta smartphones a impressoras HP para imprimir remotamente."
"Aplicativos de controle de acesso corporativo exigem autenticação multifator."
"O Microsoft Authenticator gera códigos de verificação para login seguro."
"Aplicativos de rastreamento de veículos exibem a posição em tempo real no mapa."
"Aplicativos de multas e licenciamento permitem consultar débitos de veículos."
"O Detran.SP possui aplicativo para consulta de pontos na habilitação."
"Aplicativos de declaração de imposto de renda permitem envio diretamente pelo smartphone."
"A Receita Federal disponibiliza o aplicativo Meu Imposto de Renda para dispositivos móveis."
"Aplicativos de previdência social permitem consultar extrato e agendamentos."
"O Meu INSS permite agendar serviços e emitir extratos pelo smartphone."
"Aplicativos de governo digital centralizam serviços públicos em uma plataforma única."
"O Gov.br é a plataforma digital do governo federal brasileiro com aplicativo móvel."
"Aplicativos de saúde pública permitem agendar consultas e exames pelo SUS."
"Aplicativos de carteira digital armazenam documentos como CNH e RG digitais."
"A CNH Digital é disponibilizada pelo Denatran através de aplicativo oficial."
"Aplicativos de pagamento por aproximação utilizam tecnologia NFC."
"O Google Pay e o Apple Pay permitem pagamentos por aproximação com o smartphone."
"Aplicativos de fidelidade armazenam pontos e oferecem recompensas ao consumidor."
"O Smiles é um programa de fidelidade com aplicativo para acúmulo de milhas."
"Aplicativos de doação permitem contribuir financeiramente para causas sociais."
"Aplicativos de voluntariado conectam pessoas a oportunidades de trabalho voluntário."
"Aplicativos de petição online coletam assinaturas digitais para causas diversas."
"O Change.org é uma plataforma de petições com versão para dispositivos móveis."
"Aplicativos de clima utilizam dados de estações meteorológicas distribuídas globalmente."
"Aplicativos de astronomia identificam estrelas e constelações apontando a câmera para o céu."
"O Star Walk usa realidade aumentada para identificar objetos celestes em tempo real."
"Aplicativos de identificação de plantas utilizam inteligência artificial para análise de imagens."
"O PlantNet compara fotos com um banco de dados de espécies vegetais cadastradas."
"Aplicativos de identificação de animais permitem reconhecer espécies pela fotografia."
"Aplicativos de mapeamento coletivo permitem que usuários relatem problemas urbanos."
"O Colab é um aplicativo para reportar problemas em cidades brasileiras."
"Aplicativos de transporte escolar monitoram a rota e a localização do ônibus."
"Aplicativos de aviação exibem voos em tempo real com altitude e velocidade."
"O Flightradar24 rastreia mais de 180.000 voos diários em todo o mundo."
"Aplicativos de navegação marítima exibem cartas náuticas e rotas para embarcações."
"Aplicativos de rádio amador permitem comunicação por frequência via smartphone."
"Aplicativos de controle de estoque registram entradas e saídas de produtos."
"Aplicativos de ponto eletrônico registram a jornada de trabalho dos funcionários."
"Aplicativos de CRM armazenam informações de clientes e histórico de interações."
"O Salesforce possui aplicativo móvel para acesso ao CRM em campo."
"Aplicativos de e-mail marketing gerenciam listas, campanhas e métricas de abertura."
"O Mailchimp possui aplicativo para acompanhar campanhas de e-mail pelo smartphone."
"Aplicativos de análise de dados exibem relatórios e gráficos em painéis interativos."
"O Google Analytics possui aplicativo para monitoramento de tráfego de sites."
"Aplicativos de anúncios permitem criar e gerenciar campanhas em redes sociais."
"O Meta Ads Manager permite gerenciar anúncios do Facebook e Instagram pelo smartphone."
"Aplicativos de atendimento ao cliente centralizam tickets e conversas em um único lugar."
"O Zendesk possui aplicativo móvel para gestão de suporte ao cliente."
"Aplicativos de videoaula permitem assistir a cursos gravados ou ao vivo."
"O Coursera oferece cursos de universidades internacionais com aplicativo móvel."
"Aplicativos de bibliotecas digitais permitem empréstimo de ebooks gratuitamente."
"O Minha Biblioteca oferece acesso a obras acadêmicas para estudantes brasileiros."
"Aplicativos de simulado preparam candidatos para provas como ENEM e concursos."
"O Stoodi e o ENEM oficial são aplicativos de preparação para o vestibular brasileiro."
"Aplicativos de acessibilidade convertem texto em voz para pessoas com deficiência visual."
"O VLibras traduz conteúdo para Libras em dispositivos Android e iOS."
"Aplicativos de comunicação alternativa auxiliam pessoas não verbais a se expressarem."
"O Boardmaker é uma ferramenta de comunicação alternativa em formato digital."
"Aplicativos de realidade virtual requerem óculos VR para experiência imersiva completa."
"O YouTube VR permite assistir vídeos em 360 graus com headsets compatíveis."
"Aplicativos de inteligência artificial geram textos, imagens e áudios por comandos."
"O ChatGPT possui aplicativo oficial para iOS e Android com acesso a modelos de linguagem."
"Aplicativos de detecção de deepfake analisam vídeos em busca de manipulações digitais."
"Aplicativos de proteção de privacidade bloqueiam rastreadores e cookies de terceiros."
"O DuckDuckGo Privacy Browser bloqueia rastreadores durante a navegação."
"Aplicativos de limpeza de armazenamento identificam e excluem arquivos desnecessários."
"O Files by Google ajuda a liberar espaço removendo arquivos duplicados e temporários."
"Aplicativos de gerenciamento de bateria monitoram o consumo energético por aplicativo."
"Aplicativos de configuração de roteadores permitem gerenciar a rede Wi-Fi doméstica."
"O app do roteador Eero permite controlar dispositivos conectados à rede."
"Aplicativos de benchmark medem o desempenho do processador e da GPU do dispositivo."
"O AnTuTu é um dos benchmarks de desempenho mais utilizados em smartphones Android."
"Aplicativos de diagnóstico identificam falhas em sensores e componentes de hardware."
"O CPU-Z exibe informações detalhadas sobre processador, memória e tela do dispositivo."'''

linhas = [l.strip() for l in RAW.split('\n') if l.strip()]
print(f'Total bruto: {len(linhas)}')

problemas = [(i, l) for i, l in enumerate(linhas) if not (l.startswith('"') and l.endswith('"'))]
if problemas:
    print(f'⚠️ Linhas suspeitas: {len(problemas)}')
    for i, l in problemas[:3]: print(f'  L{i}: {l[:80]}')

linhas_200 = linhas[:200]
print(f'Final: {len(linhas_200)} linhas')

out = os.path.join('dados', 'brutos_apps', 'neutral_claude_01.csv')
with io.open(out, 'w', encoding='utf-8', newline='\n') as f:
    f.write('\n'.join(linhas_200) + '\n')
print(f'Salvo: {out} ({os.path.getsize(out)} bytes)')
