# -*- coding: utf-8 -*-
"""Salva as frases POSITIVAS de Apps geradas pelo Gemini 3.1 pro."""
import os, io

RAW = '''"Excelente aplicativo, superou todas as minhas expectativas."
"Uso todos os dias e não consigo mais viver sem ele."
"A interface é muito intuitiva e fácil de usar."
"Nunca vi um app tão rápido e sem travamentos."
"Recomendo para todo mundo, vale muito a pena baixar."
"As novas atualizações deixaram o aplicativo ainda melhor."
"Design limpo, bonito e muito agradável aos olhos."
"Cumpre exatamente o que promete, nota dez!"
"O suporte ao cliente é rápido e resolveu meu problema."
"Melhor aplicativo da categoria, sem dúvidas."
"Muito leve, não ocupa quase nada de espaço no celular."
"Economiza muito o meu tempo na correria do dia a dia."
"Funciona perfeitamente offline, o que é um grande diferencial."
"Não tem anúncios irritantes, a experiência é muito fluida."
"As funcionalidades são completas e atendem todas as necessidades."
"Amei a facilidade de sincronização entre os meus dispositivos."
"Vale cada centavo da versão premium, investimento garantido."
"É incrível como esse app facilita a minha rotina."
"Nunca tive problemas de lentidão desde que instalei."
"A equipe de desenvolvedores está de parabéns pela ferramenta."
"Uma obra-prima dos aplicativos móveis, muito bem pensado."
"Gostei muito da nova paleta de cores e do layout atual."
"A navegação é tão suave que dá gosto de usar."
"Meus amigos me indicaram e eu também vou indicar para todos."
"Finalmente um aplicativo que respeita a privacidade do usuário."
"Os widgets disponíveis para a tela inicial são fantásticos."
"Tem todas as ferramentas que eu procurava em um só lugar."
"Não consome muita bateria, posso usar o dia inteiro."
"O tutorial inicial é muito claro e ajuda bastante."
"A segurança do aplicativo me deixa muito tranquilo para usá-lo."
"Um dos poucos apps que realmente entregam o que oferecem."
"As notificações são muito úteis e nada invasivas."
"Sempre recebo respostas rápidas quando envio sugestões."
"A organização das informações na tela é simplesmente perfeita."
"É tão fácil de usar que até minha avó conseguiu aprender."
"O modo escuro deste aplicativo é o mais bonito que já vi."
"As atualizações constantes mostram o comprometimento da equipe."
"Me ajudou muito a organizar minha vida financeira."
"Não sei como vivi tanto tempo sem essa ferramenta incrível."
"É o primeiro aplicativo que abro quando acordo."
"Desempenho impecável mesmo no meu celular mais antigo."
"A integração com outros aplicativos do meu celular é excelente."
"O melhor design de interface do usuário que já experimentei."
"Resolvi todos os meus problemas com apenas alguns cliques."
"As funções gratuitas já são mais do que suficientes para mim."
"Muito estável, nunca fechou sozinho na minha mão."
"A precisão das informações fornecidas pelo app é impressionante."
"Gosto muito das dicas e tutoriais que aparecem no aplicativo."
"Fez meu nível de produtividade aumentar absurdamente."
"Uma ferramenta essencial para qualquer estudante ou profissional."
"A qualidade gráfica é muito superior à dos concorrentes."
"A customização do perfil deixa o aplicativo com a minha cara."
"É muito prático fazer buscas e encontrar o que preciso."
"O suporte técnico é extremamente educado e eficiente."
"A versão gratuita é maravilhosa e sem propagandas abusivas."
"Sensacional! Um dos melhores downloads que já fiz."
"Aplicativo muito bem programado, sem bugs aparentes."
"A comunidade de usuários dentro do app é muito prestativa."
"O carregamento das telas é quase instantâneo."
"As opções de filtro ajudam muito nas pesquisas."
"Não trava de jeito nenhum, a fluidez é maravilhosa."
"Sempre que preciso, o aplicativo me salva rapidamente."
"A transição entre as abas é muito suave e agradável."
"O layout moderno deixa a experiência de uso muito premium."
"Até agora, não encontrei nenhum defeito neste app."
"A melhor opção do mercado atualmente, sem qualquer dúvida."
"Ficou muito mais fácil gerenciar minhas tarefas com ele."
"O reconhecimento facial para entrar no app funciona perfeitamente."
"A tradução para o português está impecável e natural."
"Estou viciado neste aplicativo, uso a toda hora."
"A estabilidade do sistema me surpreendeu muito positivamente."
"Uma solução genial para um problema cotidiano."
"Nunca vi uma plataforma tão completa e bem estruturada."
"O design minimalista é exatamente o que eu procurava."
"As animações do aplicativo são muito divertidas e bem feitas."
"O backup em nuvem me dá muita segurança e tranquilidade."
"É um aplicativo que realmente se preocupa com a acessibilidade."
"A rapidez com que as fotos carregam é impressionante."
"Sinto que meu celular ficou até melhor com esse app."
"O sistema de recompensas é muito estimulante e divertido."
"É muito fácil compartilhar os resultados com meus amigos."
"As atualizações sempre trazem novidades úteis e interessantes."
"Um app indispensável para quem gosta de tecnologia."
"A facilidade de cadastro me ganhou nos primeiros minutos."
"O painel de controle é muito intuitivo e organizado."
"A forma como os dados são apresentados é muito clara."
"Um serviço de primeiríssima qualidade na palma da mão."
"Os recursos exclusivos valem muito a pena conhecer."
"É impressionante a quantidade de funções gratuitas disponíveis."
"O aplicativo me ajuda a manter o foco nas minhas metas."
"O melhor atendimento in-app que já tive a oportunidade de usar."
"A experiência do usuário foi pensada nos mínimos detalhes."
"Um aplicativo robusto, porém muito leve e dinâmico."
"Adoro a possibilidade de personalizar os temas do app."
"A clareza das fontes torna a leitura muito confortável."
"O sistema de busca por voz funciona de maneira fantástica."
"A integração com smartwatch é perfeita e sem atrasos."
"O algoritmo de recomendação sempre acerta o que eu quero."
"Um exemplo a ser seguido por outros desenvolvedores de apps."
"Estou muito satisfeito com todas as funcionalidades oferecidas."
"O som e os alertas do app são muito bem produzidos."
"A navegação por gestos facilita muito o uso com uma mão."
"A rapidez na resposta dos comandos de toque é excelente."
"Um projeto muito bem executado do início ao fim."
"As métricas e gráficos gerados pelo app são sensacionais."
"É o tipo de aplicativo que facilita a vida da gente."
"A autenticação em duas etapas me passa muita segurança."
"O leitor de QR Code integrado é super rápido e preciso."
"Uma verdadeira mão na roda para momentos de urgência."
"O aplicativo funciona muito bem mesmo com internet fraca."
"A quantidade de conteúdo disponível na plataforma é gigantesca."
"O aplicativo é tão bom que parece até mágica."
"A qualidade de áudio das chamadas pelo app é cristalina."
"Sempre descubro uma função nova e útil navegando por ele."
"A tela principal tem tudo o que preciso de forma acessível."
"O aplicativo não pede permissões desnecessárias, amei isso."
"Uma ferramenta poderosa que cabe no meu bolso."
"O carregamento inicial do aplicativo leva apenas alguns segundos."
"As dicas de saúde e bem-estar do app são maravilhosas."
"A facilidade de fazer pagamentos por ele mudou minha rotina."
"Um sistema impecável, não tenho do que reclamar."
"O histórico de uso é muito detalhado e fácil de consultar."
"Adoro receber os relatórios semanais que o app gera."
"A opção de salvar favoritos é muito prática e eficiente."
"O design das abas de navegação é muito ergonômico."
"É nítido o cuidado dos criadores com a qualidade final."
"A funcionalidade de leitura offline salva a minha vida no metrô."
"Os filtros de imagem do aplicativo são de qualidade profissional."
"A sincronização com a minha agenda foi feita automaticamente."
"Um excelente custo-benefício, recomendo de olhos fechados."
"As ferramentas de edição são muito completas e fáceis de usar."
"O modo de economia de energia dentro do app é genial."
"A precisão do GPS integrado é a melhor que já vi."
"O aplicativo me ensinou muito com suas funções educativas."
"Uma das melhores interfaces de usuário dos últimos anos."
"O processo de recuperação de senha foi rápido e sem burocracia."
"A central de ajuda respondeu minhas dúvidas instantaneamente."
"Os tutoriais em vídeo dentro do app são excelentes."
"O aplicativo me ajudou a criar hábitos muito mais saudáveis."
"A gestão do meu tempo melhorou muito graças a esta ferramenta."
"As notificações personalizadas chegam sempre no momento certo."
"O contraste das cores na tela facilita muito a visualização."
"Um aplicativo inovador que revolucionou o modo como eu trabalho."
"A opção de desfazer ações rapidamente evita muitas dores de cabeça."
"O design responsivo se adapta perfeitamente ao meu tablet."
"As opções de exportação de arquivos são muito versáteis."
"O aplicativo é divertido e interativo, não canso de usar."
"A galeria de imagens carrega tudo de forma muito rápida."
"Um verdadeiro assistente pessoal disfarçado de aplicativo."
"A função de auto-salvamento funciona de forma muito segura."
"O desempenho em jogos dentro da plataforma é muito suave."
"A integração com redes sociais ocorre de forma natural e fácil."
"Os ícones são bonitos e indicam claramente suas funções."
"O alerta de promoções me fez economizar muito dinheiro."
"A facilidade de cancelar a assinatura mostra o respeito ao cliente."
"O aplicativo não esquenta o aparelho, mesmo após horas de uso."
"As recomendações personalizadas parecem ler a minha mente."
"A função de câmera embutida tira fotos com ótima resolução."
"O teclado virtual do app tem uma digitação muito precisa."
"O sistema de conquistas e badges me mantém muito motivado."
"A tela de bloqueio com widgets do app é maravilhosa."
"O redimensionamento de imagens dentro do app é perfeito."
"A fluidez das transições de vídeo é digna de cinema."
"Um aplicativo que entrega excelência em cada detalhe."
"As opções de formato de texto são muito ricas e variadas."
"O aplicativo não exige criação de conta para começar a usar."
"A barra de progresso visual é muito útil nos downloads."
"O leitor de PDF integrado abre arquivos pesados num piscar de olhos."
"A função de agendamento de tarefas é incrivelmente prática."
"O aplicativo nunca exibiu um erro desde que comecei a usar."
"A integração com os assistentes de voz funciona de forma nativa."
"A galeria de modelos prontos ajuda muito na criação rápida."
"A privacidade dos dados é tratada com muita seriedade aqui."
"O modo noturno automático acompanha o sistema perfeitamente."
"As opções de compartilhamento rápido agilizam meu trabalho."
"A qualidade da conversão de arquivos pelo aplicativo é excelente."
"O aplicativo consegue ser complexo em funções e simples de usar."
"A resposta do leitor de digital no login é imediata."
"A facilidade de trocar de conta dentro do app é ótima."
"O aplicativo é muito bem otimizado para telas grandes."
"A função de tradução simultânea é simplesmente fantástica."
"O uso de memória RAM pelo aplicativo é surpreendentemente baixo."
"As atualizações em segundo plano não atrapalham em nada o uso."
"O sistema de abas permite realizar várias tarefas ao mesmo tempo."
"A clareza das mensagens de erro ajuda a resolver tudo rápido."
"O recurso de lixeira garante que não perderei dados por acidente."
"O aplicativo manteve a alta qualidade mesmo após as atualizações recentes."
"A ferramenta de recorte e edição de áudio é fenomenal."
"O suporte multi-idiomas atende usuários do mundo todo com maestria."
"A visualização em formato de calendário organiza minha semana toda."
"Um dos aplicativos mais úteis e incríveis da minha biblioteca."
"As animações de loading são tão criativas que nem vejo o tempo passar."
"O sistema de favoritos em pastas deixa tudo mais organizado."
"Simplesmente brilhante, um exemplo de perfeição em formato de aplicativo."'''

linhas = [l.strip() for l in RAW.split('\n') if l.strip()]
print(f'Total bruto: {len(linhas)}')

problemas = [(i, l) for i, l in enumerate(linhas) if not (l.startswith('"') and l.endswith('"'))]
if problemas:
    print(f'⚠️ Linhas suspeitas: {len(problemas)}')
    for i, l in problemas[:3]: print(f'  L{i}: {l[:80]}')

linhas_200 = linhas[:200]
print(f'Final: {len(linhas_200)} linhas')

out = os.path.join('dados', 'brutos_apps', 'positive_gemini_01.csv')
with io.open(out, 'w', encoding='utf-8', newline='\n') as f:
    f.write('\n'.join(linhas_200) + '\n')
print(f'Salvo: {out} ({os.path.getsize(out)} bytes)')
