# -*- coding: utf-8 -*-
"""Salva as frases POSITIVAS de Apps geradas pelo Claude Sonnet 4.6 adaptativo."""
import os, io

RAW = '''"Aplicativo incrível, superou todas as minhas expectativas desde o primeiro uso.",
"Interface linda e intuitiva, naveguei sem dificuldade alguma desde o início.",
"Carregamento super rápido, não preciso esperar nada para usar.",
"Melhor app que já baixei, uso todos os dias sem reclamar.",
"Design moderno e elegante, dá gosto de abrir o aplicativo.",
"Atendeu perfeitamente todas as minhas necessidades do dia a dia.",
"Funciona sem travar, mesmo no meu celular mais antigo.",
"Atualizações constantes mostram que a equipe se importa com os usuários.",
"Suporte ao cliente resolveu meu problema em menos de cinco minutos.",
"Nunca vi um app tão bem organizado e fácil de usar.",
"Economizei muito tempo depois que comecei a usar esse aplicativo.",
"Recomendo para todos os meus amigos sem hesitar.",
"Interface clara e objetiva, encontro tudo que preciso rapidamente.",
"Desempenho excepcional, roda perfeitamente sem consumir muita bateria.",
"O aplicativo transformou completamente minha rotina para melhor.",
"Cada atualização traz melhorias reais que fazem diferença no uso.",
"Simples de instalar e configurar, qualquer pessoa consegue usar.",
"Recursos poderosos que funcionam exatamente como prometido.",
"A melhor experiência de usuário que já tive em um app.",
"Notificações inteligentes, aparecem na hora certa sem incomodar.",
"Visual impecável, parece que foi feito por grandes designers.",
"Estabilidade impressionante, nunca fechou sozinho nenhuma vez.",
"Perfeito para uso profissional e pessoal ao mesmo tempo.",
"Economiza bateria enquanto entrega performance de alto nível.",
"Integração com outros apps funcionou perfeitamente na primeira tentativa.",
"Sincronização automática entre dispositivos sem perder nenhum dado.",
"Modo escuro lindo, uso à noite sem cansar a vista.",
"Processo de cadastro simples e rápido, levou menos de um minuto.",
"Funcionalidades gratuitas já entregam muito valor para o usuário.",
"Aplicativo leve que não ocupa espaço desnecessário no celular.",
"Busca interna precisa, encontro qualquer coisa em segundos.",
"Layout responsivo que se adapta perfeitamente a qualquer tela.",
"Deu um upgrade completo na forma como organizo minha vida.",
"A versão premium vale cada centavo investido sem dúvida.",
"Recebo atualizações frequentes com novas funções muito úteis.",
"Melhorou minha produtividade de forma que não imaginava possível.",
"Tutorial inicial claro e objetivo, aprendi a usar em minutos.",
"Nunca tive problema de login, acesso sempre funciona perfeitamente.",
"Excelente custo-benefício comparado a outros apps similares no mercado.",
"Dados ficam seguros e protegidos, confio totalmente na plataforma.",
"Filtros e categorias bem organizados facilitam demais a navegação.",
"Personalização perfeita, consigo deixar tudo do meu jeito.",
"Velocidade de resposta impressiona, tudo acontece instantaneamente.",
"Histórico de atividades bem detalhado e fácil de consultar.",
"Fluxo de uso natural, não precisei de nenhuma ajuda externa.",
"Excelente app para quem quer organizar a vida financeira.",
"Gráficos e relatórios visuais lindos e muito informativos.",
"Acessibilidade bem implementada, funciona ótimo para todos os usuários.",
"Animações suaves que deixam a experiência muito mais agradável.",
"Nunca perdi dados, a sincronização na nuvem é confiável.",
"Telas bem pensadas, cada elemento está exatamente onde deveria estar.",
"Configurações avançadas disponíveis sem complicar a experiência básica.",
"Compartilhamento de conteúdo funciona perfeitamente com um único toque.",
"Acabei com papel e caneta depois que comecei usar esse app.",
"Performance consistente independentemente de quantas funções uso juntas.",
"Experiência fluida do início ao fim, sem fricção alguma.",
"App que realmente cumpre tudo que promete na descrição da loja.",
"Ícones intuitivos que qualquer pessoa entende sem precisar ler.",
"Garante uma experiência premium mesmo na versão gratuita básica.",
"Melhor aplicativo de produtividade que existe nas lojas hoje.",
"Funciona offline sem perder nenhuma funcionalidade essencial importante.",
"Comunicação clara dentro do app, nada confunde o usuário.",
"Sistema de favoritos muito útil para acessar conteúdos preferidos.",
"Sem anúncios intrusivos, a experiência de uso é limpa.",
"Configuração inicial automática que detecta minhas preferências sozinha.",
"Ajuda contextual sempre disponível quando tenho alguma dúvida.",
"Lembra minhas preferências entre sessões sem precisar reconfigurar nada.",
"Destaque entre os apps da categoria, nenhum chega perto.",
"Atalhos de teclado funcionam perfeitamente para uso avançado.",
"Integração com redes sociais simplificou muito meu compartilhamento de conteúdo.",
"Versão para tablet igualmente perfeita, aproveitando bem a tela grande.",
"Tempo de resposta do suporte é admirável, muito rápido e eficiente.",
"App que recebo elogios quando mostro para colegas de trabalho.",
"Função de pesquisa avançada encontra exatamente o que procuro sempre.",
"Backup automático me salvou de perder dados importantes uma vez.",
"Interface consistente em todas as telas, experiência muito coerente.",
"Consegui migrar do concorrente sem perder nenhum dado importante.",
"Recursos de acessibilidade exemplares, inclusivo para todos os usuários.",
"Paleta de cores harmoniosa que deixa tudo agradável visualmente.",
"Nunca apresentou bug sequer, estabilidade de nível profissional.",
"Cumpre a promessa de privacidade, me sinto seguro usando.",
"Fluxo de pagamento simples e seguro, comprei sem preocupação.",
"Excelente para equipes, colaboração em tempo real funciona perfeitamente.",
"Importação de dados do concorrente funcionou sem nenhum problema.",
"Controles parentais completos e fáceis de configurar rapidamente.",
"Gestos intuitivos que tornam a navegação muito mais rápida.",
"Widget para tela inicial muito útil e bem desenhado.",
"Relatórios exportáveis em vários formatos, super conveniente no trabalho.",
"Aplicativo que indico para toda a família sem reservas.",
"Funciona impecavelmente mesmo com conexão de internet mais lenta.",
"Categorização automática de conteúdo economiza muito trabalho manual.",
"Reminders inteligentes no momento certo sem ser invasivo.",
"Excelente controle de privacidade, escolho o que compartilhar.",
"Compatível com meu smartwatch, integração perfeita entre dispositivos.",
"App mais confiável que já usei em anos de smartphone.",
"Novas funcionalidades adicionadas sem complicar a interface existente.",
"Encontrei comunidade incrível de usuários dentro do próprio app.",
"Login biométrico rápido e seguro, acesso instantâneo sempre.",
"Tutoriais em vídeo dentro do app são claros e objetivos.",
"Histórico de atualizações mostra evolução constante e comprometida.",
"Consumo de dados móveis muito baixo, ótimo para planos limitados.",
"App que me faz querer abrir o celular com prazer.",
"Conquistas e recompensas dentro do app tornam tudo mais divertido.",
"Compatibilidade total com meu modelo de celular mais antigo.",
"Feedback háptico bem calibrado, resposta tátil muito agradável.",
"Gerenciamento de armazenamento eficiente, não enche a memória do celular.",
"Clareza nas notificações, sempre sei exatamente o que aconteceu.",
"Ordenação e filtragem de conteúdo extremamente precisa e rápida.",
"Interface que não cansa os olhos mesmo após horas de uso.",
"Criação de conta sem pedir informações desnecessárias, respeito pela privacidade.",
"Funcionalidade de busca por voz funciona perfeitamente em português.",
"Histórico de uso bem detalhado para acompanhar meu progresso.",
"Aplicativo que realmente me ajudou a economizar dinheiro todo mês.",
"Respostas automáticas inteligentes que economizam meu tempo diariamente.",
"Compatível com assistentes de voz, integração funcionou na primeira vez.",
"Métricas em tempo real muito úteis para acompanhar resultados.",
"Segurança de dois fatores bem implementada e fácil de ativar.",
"App gratuito que entrega mais valor que muitos pagos.",
"Personalização de tema e cores deixa o app com minha cara.",
"Recursos colaborativos que facilitaram muito o trabalho em equipe.",
"Transições entre telas suaves e rápidas, experiência muito polida.",
"App que recomendo com entusiasmo para qualquer pessoa.",
"Configuração de preferências salva na nuvem, nunca perco minhas escolhas.",
"Processo de compra dentro do app simples e muito seguro.",
"Curadoria de conteúdo inteligente que aprende minhas preferências rapidamente.",
"Design limpo sem poluição visual, foco no que importa.",
"Recursos de edição poderosos com interface amigável e acessível.",
"Aplicativo essencial que não consigo mais imaginar minha vida sem.",
"Tamanho do arquivo pequeno mas com funcionalidades de alto nível.",
"Comunidade ativa dentro do app com conteúdo sempre relevante.",
"Configurações de notificação granulares para controle total do usuário.",
"Performance não cai mesmo depois de semanas de uso contínuo.",
"Opção de múltiplos idiomas bem implementada, troca sem reiniciar.",
"App que realmente entende o que o usuário precisa.",
"Sistema de avaliação interno justo e bem estruturado.",
"Tempo de inicialização muito rápido, abre em um segundo.",
"Exportação de dados completa e em formato aberto e acessível.",
"App que me faz poupar tempo todo dia de forma consistente.",
"Funcionalidade de desfazer operações salvou meu trabalho várias vezes.",
"Ótima experiência de onboarding, aprendi tudo rápido e naturalmente.",
"App que evoluiu muito desde a primeira versão que usei.",
"Políticas de reembolso claras e respeitadas pela equipe sem burocracia.",
"Multi-conta funcionando perfeitamente, alterno entre perfis com facilidade.",
"Gráficos de progresso motivadores que me mantêm engajado diariamente.",
"Integrações com outros serviços que uso funcionaram sem configuração manual.",
"Modo offline robusto, uso tranquilamente sem internet disponível.",
"Comentários da comunidade dentro do app são úteis e moderados.",
"Ferramenta de colaboração que substituiu vários outros apps de vez.",
"Aplicativo que me ajudou a criar hábitos saudáveis de verdade.",
"Suporte a múltiplos arquivos simultâneos sem travar ou lentidão.",
"Área de configurações bem organizada e fácil de entender.",
"App que supera qualquer concorrente que já experimentei antes.",
"Recurso de repetição espaçada muito bem implementado e eficiente.",
"Notificações de segurança imediatas me deixam sempre tranquilo.",
"Listas de tarefas colaborativas funcionando perfeitamente em tempo real.",
"Melhor app de finanças pessoais disponível nas lojas atualmente.",
"Sem propagandas invasivas que interrompam o fluxo de trabalho.",
"Sistema de conquistas que mantém a motivação alta sempre.",
"Performance de câmera integrada muito acima do esperado.",
"Separação de conteúdo por categorias muito bem pensada e útil.",
"Atalhos gestuais que aprendi rápido e uso constantemente.",
"Opções de exportação variadas que atendem todas as minhas necessidades.",
"Aplicativo transformou meu hobby em algo mais organizado e produtivo.",
"Funcionalidade de backup e restauração funcionou perfeitamente quando precisei.",
"Layout adaptável que funciona bem tanto em modo retrato quanto paisagem.",
"Sistema de busca avançada com filtros que realmente funcionam.",
"App com curva de aprendizado baixa mas profundidade de recursos alta.",
"Integração com calendário nativo do celular funcionou imediatamente.",
"Gerenciamento de assinaturas claro e transparente sem surpresas.",
"App que recomendo especificamente para quem quer ser mais produtivo.",
"Recursos premium acessíveis com preço justo pelo valor entregue.",
"Atualizações de segurança frequentes mostram comprometimento da equipe.",
"Feedback visual imediato em cada ação que realizo no app.",
"Separação clara entre dados pessoais e profissionais bem implementada.",
"Multi-plataforma perfeito, dados sincronizam entre celular e computador.",
"Usabilidade excepcional que torna o app indispensável no cotidiano.",
"Nunca tive problema de perda de dados em nenhuma circunstância.",
"Controles de privacidade detalhados que me dão paz de espírito.",
"Interface que parece ter sido projetada especificamente para mim.",
"Melhor investimento em aplicativo que já fiz na vida.",
"Performance estável durante chamadas de vídeo longas sem interrupção.",
"App que impressiona até pessoas que não gostam de tecnologia.",
"Recurso de destaques automáticos muito preciso e útil no dia a dia.",
"Aplicativo que cumpre promessas e vai além das expectativas.",
"Experiência consistente entre todas as versões e atualizações lançadas.",
"Onboarding personalizado que se adapta ao meu nível de experiência.",
"App que eu nunca desinstalo e sempre recomendo para todos.",
"Desempenho excepcional mesmo quando uso múltiplos recursos simultaneamente.",
"Interface tão boa que aprendi a usar sem ler nenhum tutorial.",
"Aplicativo que gerou impacto real e positivo na minha vida.",
"Melhor app que a loja de aplicativos me recomendou até hoje.",
"Funcionalidade de compartilhamento rápida e sem etapas desnecessárias.",
"App com comunidade ativa que agrega muito valor à experiência.",
"Recursos que continuam surpreendendo depois de meses de uso diário.",
"Política de privacidade transparente que gera confiança genuína no app.",
"App que simplesmente funciona, sem complicação nem decepção alguma."'''

linhas = [l.strip() for l in RAW.split('\n') if l.strip()]
linhas_limpas = [l[:-1] if l.endswith('",') else l for l in linhas]
print(f'Total bruto: {len(linhas_limpas)}')

problemas = [(i, l) for i, l in enumerate(linhas_limpas) if not (l.startswith('"') and l.endswith('"'))]
if problemas:
    print(f'⚠️ Linhas suspeitas: {len(problemas)}')
    for i, l in problemas[:3]: print(f'  L{i}: {l[:80]}')

linhas_200 = linhas_limpas[:200]
print(f'Final: {len(linhas_200)} linhas')

out = os.path.join('dados', 'brutos_apps', 'positive_claude_01.csv')
with io.open(out, 'w', encoding='utf-8', newline='\n') as f:
    f.write('\n'.join(linhas_200) + '\n')
print(f'Salvo: {out} ({os.path.getsize(out)} bytes)')
