# -*- coding: utf-8 -*-
"""Salva as 200 frases POSITIVAS de Apps geradas pelo ChatGPT 5.5."""
import os, io

# Conteúdo cru passado pelo Davi (formato: cada linha entre aspas, separadas por vírgula)
RAW = '''"Aplicativo excelente, rápido e muito fácil de usar no dia a dia.",
"Interface bonita, organizada e extremamente intuitiva para qualquer usuário.",
"Gostei muito da velocidade e da estabilidade do aplicativo.",
"O app funciona perfeitamente e nunca travou comigo.",
"Experiência incrível, tudo funciona de maneira simples e eficiente.",
"Aplicativo muito útil, resolveu exatamente o que eu precisava.",
"Design moderno e funcionalidades excelentes em um só aplicativo.",
"Estou muito satisfeito com a praticidade oferecida pelo app.",
"Aplicativo leve, rápido e com ótimo desempenho no celular.",
"Ferramenta excelente para organizar minha rotina diariamente.",
"O aplicativo superou minhas expectativas em todos os aspectos.",
"Muito fácil de aprender a usar e extremamente eficiente.",
"Ótimo aplicativo, interface limpa e navegação muito agradável.",
"Aplicativo confiável e com recursos realmente úteis.",
"Estou adorando usar esse aplicativo todos os dias.",
"Excelente desempenho mesmo em celulares mais simples.",
"O app possui recursos incríveis e muito bem desenvolvidos.",
"Aplicativo intuitivo, rápido e muito agradável visualmente.",
"Gostei bastante da organização e facilidade de navegação.",
"Aplicativo muito completo e fácil de configurar.",
"Experiência excelente desde o primeiro uso do aplicativo.",
"O aplicativo entrega exatamente o que promete.",
"Recursos úteis e interface extremamente amigável.",
"Aplicativo maravilhoso, tornou minhas tarefas muito mais simples.",
"Ótima experiência de uso, sem complicações desnecessárias.",
"Aplicativo bem otimizado e com excelente desempenho.",
"Ferramenta fantástica para produtividade e organização pessoal.",
"Gostei muito da qualidade e estabilidade do aplicativo.",
"Aplicativo moderno e muito eficiente para o dia a dia.",
"Excelente aplicativo, rápido e sem anúncios excessivos.",
"Estou impressionado com a qualidade desse app.",
"Aplicativo muito bem feito e agradável de utilizar.",
"Funciona perfeitamente e possui ótimos recursos gratuitos.",
"Aplicativo simples, eficiente e muito confiável.",
"Experiência fluida e muito agradável em todas as funções.",
"Ótimo aplicativo para quem busca praticidade e rapidez.",
"Gostei bastante da interface moderna e elegante.",
"Aplicativo excelente para organizar tarefas e compromissos.",
"Tudo funciona de forma rápida e sem travamentos.",
"Aplicativo muito útil e com ótima experiência visual.",
"Excelente qualidade e recursos muito bem planejados.",
"Aplicativo intuitivo e extremamente funcional no cotidiano.",
"Gostei muito da facilidade de acesso às funções.",
"Aplicativo completo e muito fácil de navegar.",
"Ótima performance e excelente estabilidade no celular.",
"Aplicativo realmente facilita minha rotina diariamente.",
"Experiência positiva desde a instalação até o uso contínuo.",
"Gostei bastante das atualizações e melhorias constantes.",
"Aplicativo rápido, bonito e muito eficiente.",
"Excelente aplicativo, fácil de usar e muito prático.",
"Recursos incríveis e interface muito agradável visualmente.",
"Aplicativo muito organizado e simples de entender.",
"Ótima ferramenta para aumentar a produtividade diária.",
"Aplicativo extremamente útil e com ótima navegação.",
"Gostei da simplicidade sem perder funcionalidades importantes.",
"Aplicativo confiável e muito estável durante o uso.",
"Experiência excelente com recursos realmente funcionais.",
"Aplicativo leve e muito rápido para abrir funções.",
"Gostei muito do visual moderno e da praticidade.",
"Excelente aplicativo para uso pessoal e profissional.",
"Aplicativo muito bem desenvolvido e fácil de utilizar.",
"Ótima experiência, tudo funciona perfeitamente no celular.",
"Aplicativo intuitivo e extremamente eficiente nas tarefas.",
"Gostei muito da velocidade e organização do app.",
"Aplicativo muito prático para o dia a dia corrido.",
"Excelente desempenho mesmo utilizando vários recursos simultaneamente.",
"Aplicativo muito agradável e simples de configurar.",
"Recursos úteis e ótima estabilidade durante o uso.",
"Aplicativo excelente para otimizar minha rotina diária.",
"Gostei muito da navegação rápida e intuitiva.",
"Aplicativo moderno e extremamente funcional.",
"Excelente ferramenta para organização e produtividade.",
"Aplicativo rápido, estável e muito fácil de usar.",
"Gostei bastante da qualidade geral do aplicativo.",
"Aplicativo intuitivo e com recursos muito interessantes.",
"Ótima experiência visual e excelente desempenho geral.",
"Aplicativo extremamente útil e muito bem organizado.",
"Gostei muito da facilidade para encontrar as funções.",
"Aplicativo excelente e com interface muito bonita.",
"Ótima estabilidade e desempenho em qualquer situação.",
"Aplicativo muito eficiente e agradável de utilizar.",
"Gostei bastante da praticidade oferecida pelo aplicativo.",
"Aplicativo completo e muito intuitivo para iniciantes.",
"Excelente qualidade e funcionamento impecável.",
"Aplicativo leve e extremamente rápido no celular.",
"Gostei muito da experiência simples e eficiente.",
"Aplicativo confiável e com ótimo suporte de recursos.",
"Excelente aplicativo para facilitar tarefas diárias.",
"Interface organizada e muito agradável visualmente.",
"Aplicativo muito estável e com ótima performance.",
"Gostei muito das funcionalidades disponíveis gratuitamente.",
"Aplicativo incrível e extremamente fácil de navegar.",
"Excelente desempenho sem consumir muitos recursos.",
"Aplicativo muito útil e intuitivo no uso diário.",
"Gostei bastante da velocidade e praticidade do app.",
"Aplicativo moderno e muito bem estruturado.",
"Excelente experiência de uso em todas as funções.",
"Aplicativo simples, rápido e extremamente eficiente.",
"Gostei muito do design limpo e organizado.",
"Aplicativo excelente para melhorar a produtividade.",
"Ótimos recursos e navegação muito intuitiva.",
"Aplicativo muito agradável e fácil de configurar.",
"Excelente estabilidade e ótimo desempenho geral.",
"Aplicativo realmente entrega uma experiência premium.",
"Gostei bastante da qualidade das funcionalidades.",
"Aplicativo intuitivo e muito confortável de usar.",
"Excelente ferramenta para organizar atividades diárias.",
"Aplicativo rápido e muito eficiente no funcionamento.",
"Gostei muito da praticidade e simplicidade oferecidas.",
"Aplicativo muito completo e funcional para qualquer usuário.",
"Excelente desempenho e ótima experiência visual.",
"Aplicativo fácil de usar e muito bem otimizado.",
"Gostei bastante da organização das funções disponíveis.",
"Aplicativo extremamente útil e muito confiável.",
"Excelente qualidade e interface muito moderna.",
"Aplicativo rápido e estável durante todo o uso.",
"Gostei muito da navegação simples e eficiente.",
"Aplicativo excelente para produtividade e organização.",
"Ótima experiência com recursos bem desenvolvidos.",
"Aplicativo muito leve e fácil de utilizar.",
"Gostei bastante da eficiência e praticidade do app.",
"Aplicativo moderno e muito intuitivo para qualquer pessoa.",
"Excelente estabilidade e rapidez nas funções.",
"Aplicativo muito útil e agradável visualmente.",
"Gostei muito da simplicidade e funcionalidade oferecidas.",
"Aplicativo excelente para facilitar tarefas do cotidiano.",
"Ótimos recursos e excelente desempenho no celular.",
"Aplicativo intuitivo e muito fácil de configurar.",
"Gostei bastante da experiência fluida e organizada.",
"Aplicativo rápido, bonito e extremamente funcional.",
"Excelente ferramenta para melhorar minha rotina diária.",
"Aplicativo muito estável e com ótima usabilidade.",
"Gostei muito das funções simples e eficientes.",
"Aplicativo completo e muito agradável de usar.",
"Excelente desempenho e recursos realmente úteis.",
"Aplicativo muito bem desenvolvido e intuitivo.",
"Gostei bastante da interface limpa e moderna.",
"Aplicativo eficiente e muito prático para o cotidiano.",
"Excelente aplicativo com ótima experiência de navegação.",
"Aplicativo rápido e muito confiável diariamente.",
"Gostei muito da qualidade e organização do app.",
"Aplicativo muito intuitivo e fácil de aprender.",
"Excelente estabilidade e ótimo funcionamento geral.",
"Aplicativo bonito e extremamente eficiente nas tarefas.",
"Gostei bastante da rapidez e praticidade oferecidas.",
"Aplicativo excelente e muito agradável visualmente.",
"Ótima experiência com recursos úteis e simples.",
"Aplicativo muito funcional e fácil de navegar.",
"Gostei muito do desempenho rápido e estável.",
"Aplicativo excelente para organizar compromissos diariamente.",
"Ótima interface e navegação extremamente intuitiva.",
"Aplicativo muito útil e eficiente em qualquer momento.",
"Gostei bastante da qualidade visual e funcionalidade.",
"Aplicativo rápido, moderno e muito fácil de usar.",
"Excelente desempenho sem apresentar travamentos.",
"Aplicativo extremamente intuitivo e organizado.",
"Gostei muito da simplicidade e eficiência do app.",
"Aplicativo muito estável e agradável no uso diário.",
"Excelente aplicativo com recursos realmente interessantes.",
"Aplicativo leve e com ótimo desempenho geral.",
"Gostei bastante da navegação rápida e prática.",
"Aplicativo moderno e muito bem otimizado.",
"Excelente experiência desde o primeiro acesso.",
"Aplicativo muito funcional e intuitivo para qualquer idade.",
"Gostei muito das atualizações constantes e melhorias.",
"Aplicativo excelente e extremamente confiável.",
"Ótima organização e facilidade de utilização.",
"Aplicativo muito eficiente e com ótima estabilidade.",
"Gostei bastante da interface bonita e moderna.",
"Aplicativo rápido e muito agradável de usar.",
"Excelente ferramenta para facilitar minha organização.",
"Aplicativo intuitivo e muito bem estruturado.",
"Gostei muito da praticidade oferecida diariamente.",
"Aplicativo excelente com ótimo desempenho no celular.",
"Ótimos recursos e experiência muito positiva.",
"Aplicativo muito leve e extremamente funcional.",
"Gostei bastante da velocidade e estabilidade do app.",
"Aplicativo moderno e muito eficiente nas tarefas.",
"Excelente experiência de uso sem complicações.",
"Aplicativo muito útil para organização pessoal.",
"Gostei muito da navegação simples e rápida.",
"Aplicativo excelente e com ótima interface visual.",
"Ótima qualidade e desempenho durante o uso.",
"Aplicativo muito intuitivo e fácil de configurar.",
"Gostei bastante da funcionalidade e praticidade.",
"Aplicativo rápido, confiável e muito eficiente.",
"Excelente aplicativo para melhorar a produtividade diária.",
"Aplicativo muito agradável e com ótima navegação.",
"Gostei muito da experiência visual e desempenho.",
"Aplicativo excelente e extremamente estável.",
"Ótimos recursos gratuitos e funcionamento impecável.",
"Aplicativo muito fácil de usar e configurar.",
"Gostei bastante da praticidade oferecida pelo sistema.",
"Aplicativo rápido e muito organizado visualmente.",
"Excelente desempenho em todas as funcionalidades.",
"Aplicativo muito útil e bem desenvolvido.",
"Gostei muito da simplicidade e eficiência geral.",
"Aplicativo excelente para facilitar tarefas cotidianas.",
"Ótima estabilidade e navegação muito intuitiva.",
"Aplicativo moderno e extremamente agradável de utilizar.",
"Gostei bastante da velocidade e funcionalidade.",
"Aplicativo eficiente e muito confiável diariamente.",
"Excelente aplicativo com recursos muito úteis.",
"Aplicativo muito leve e com ótima usabilidade.",
"Gostei muito da interface organizada e bonita.",
"Aplicativo rápido e extremamente funcional no celular.",
"Excelente experiência e ótimo desempenho geral.",
"Aplicativo muito intuitivo e agradável visualmente.",
"Gostei bastante da facilidade de utilização.",
"Aplicativo excelente e muito bem otimizado.",
"Ótima ferramenta para aumentar minha produtividade.",
"Aplicativo muito eficiente e fácil de navegar.",
"Gostei muito da qualidade e estabilidade oferecidas.",
"Aplicativo moderno, rápido e extremamente útil.",
"Excelente desempenho e ótima experiência diária.",
"Aplicativo muito agradável e intuitivo para qualquer usuário.",
"Gostei bastante da praticidade e organização do app.",
"Aplicativo excelente com recursos simples e eficientes.",
"Ótima navegação e desempenho muito satisfatório.",
"Aplicativo rápido, funcional e muito confiável.",
"Gostei muito da experiência geral com o aplicativo.",
"Aplicativo extremamente útil e muito bem desenvolvido.",
"Excelente qualidade e ótimo funcionamento diário.",
"Aplicativo muito estável e fácil de utilizar.",
"Gostei bastante da organização e eficiência do app.",
"Aplicativo moderno e com excelente desempenho.",
"Excelente experiência visual e ótima funcionalidade.",
"Aplicativo muito intuitivo e extremamente rápido.",
"Gostei muito da praticidade oferecida no cotidiano.",
"Aplicativo excelente e muito eficiente nas tarefas.",
"Ótimos recursos e navegação bastante agradável.",
"Aplicativo muito confiável e fácil de aprender.",
"Gostei bastante da velocidade e estabilidade geral.",
"Aplicativo rápido, bonito e extremamente funcional.",
"Excelente ferramenta para facilitar minha rotina.",
"Aplicativo muito organizado e agradável de utilizar.",
"Gostei muito da eficiência e simplicidade do aplicativo."'''

# Processa: cada linha termina com `",` (exceto a última que termina só com `"`)
# Normalizamos: removemos a vírgula final de cada linha
linhas = [l.strip() for l in RAW.split('\n') if l.strip()]
# Cada linha tem que terminar com aspas, sem vírgula
linhas_limpas = [l[:-1] if l.endswith('",') else l for l in linhas]

print(f'Total de frases: {len(linhas_limpas)}')
print(f'Primeira: {linhas_limpas[0]}')
print(f'Última: {linhas_limpas[-1]}')

# Valida que cada linha começa e termina com aspas
problemas = [(i, l) for i, l in enumerate(linhas_limpas) if not (l.startswith('"') and l.endswith('"'))]
if problemas:
    print(f'\n⚠️ Linhas com formato suspeito: {len(problemas)}')
    for i, l in problemas[:3]:
        print(f'  L{i}: {l}')
else:
    print('Formato OK em todas as linhas.')

# Salva
out = os.path.join('dados', 'brutos_apps', 'positive_gpt_01.csv')
with io.open(out, 'w', encoding='utf-8', newline='\n') as f:
    f.write('\n'.join(linhas_limpas) + '\n')
print(f'\nSalvo: {out}')
print(f'Tamanho: {os.path.getsize(out)} bytes')
