# -*- coding: utf-8 -*-
"""Atualiza a célula final do notebook 03 para gerar gráficos das 4 métricas."""
import nbformat as nbf
import io

nb_path = 'src/03_movies_3_visoes.ipynb'
with io.open(nb_path, 'r', encoding='utf-8') as f:
    nb = nbf.read(f, as_version=4)

# Célula 11 (índice 11) — Resultado final com TODAS as 4 métricas
nb.cells[11].source = (
    "# ============================================================\n"
    "# RESULTADO FINAL: tabela + grafico (4 metricas) + salvar\n"
    "# ============================================================\n"
    "import matplotlib.pyplot as plt\n"
    "\n"
    "df_resultados = pd.DataFrame(todos_resultados)\n"
    "\n"
    "# Ordem fixa das visoes\n"
    "ordem_visoes = ['V1: Sintético → Sintético', 'V2: Real → Real', 'V3: Sintético → Real']\n"
    "df_resultados['Visão'] = pd.Categorical(df_resultados['Visão'], "
    "categories=ordem_visoes, ordered=True)\n"
    "df_resultados = df_resultados.sort_values(['Visão', 'Modelo']).reset_index(drop=True)\n"
    "\n"
    "ordem_modelos = ['Naive Bayes', 'Regressão Logística', 'SVM Linear']\n"
    "metricas = ['Acurácia', 'Precisão', 'Recall', 'F1-Score']\n"
    "\n"
    "# Tabela consolidada com todas as metricas (uma linha por Visao+Modelo)\n"
    "print('\\n=== METRICAS COMPLETAS — Nicho: Movies ===')\n"
    "print((df_resultados.set_index(['Visão', 'Modelo'])[metricas] * 100).round(2).to_string())\n"
    "\n"
    "# Salva CSV\n"
    "os.makedirs(RESULTADOS, exist_ok=True)\n"
    "csv_path = os.path.join(RESULTADOS, 'metricas_3_visoes_movies.csv')\n"
    "df_resultados.round(4).to_csv(csv_path, index=False)\n"
    "print(f'\\nCSV salvo: {csv_path}')\n"
    "\n"
    "# --- GRAFICO 1: painel 2x2 com as 4 metricas (um arquivo so) ---\n"
    "fig, axes = plt.subplots(2, 2, figsize=(15, 10), sharey=True)\n"
    "axes = axes.flatten()\n"
    "for i, metrica in enumerate(metricas):\n"
    "    pivot = df_resultados.pivot(index='Visão', columns='Modelo', values=metrica)[ordem_modelos]\n"
    "    pivot.plot(kind='bar', ax=axes[i], rot=15, edgecolor='black', width=0.75, legend=(i==0))\n"
    "    axes[i].set_title(metrica, fontsize=13, fontweight='bold')\n"
    "    axes[i].set_xlabel('')\n"
    "    axes[i].set_ylim(0, 1.0)\n"
    "    axes[i].grid(axis='y', alpha=0.3)\n"
    "    for container in axes[i].containers:\n"
    "        axes[i].bar_label(container, fmt='%.2f', padding=2, fontsize=8)\n"
    "    if i == 0:\n"
    "        axes[i].legend(title='Modelo', loc='upper right', fontsize=9)\n"
    "axes[0].set_ylabel('Valor (weighted)', fontsize=11)\n"
    "axes[2].set_ylabel('Valor (weighted)', fontsize=11)\n"
    "fig.suptitle('Comparativo das 3 Visões — 4 Métricas — Movies (UTLC-Movies)',\n"
    "             fontsize=14, fontweight='bold', y=1.00)\n"
    "plt.tight_layout()\n"
    "png_path = os.path.join(RESULTADOS, 'grafico_3_visoes_movies_4metricas.png')\n"
    "plt.savefig(png_path, dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print(f'Gráfico 4-em-1 salvo: {png_path}')\n"
    "\n"
    "# --- GRAFICOS INDIVIDUAIS (um por metrica, util pro artigo) ---\n"
    "for metrica in metricas:\n"
    "    pivot = df_resultados.pivot(index='Visão', columns='Modelo', values=metrica)[ordem_modelos]\n"
    "    fig, ax = plt.subplots(figsize=(10, 6))\n"
    "    pivot.plot(kind='bar', ax=ax, rot=0, edgecolor='black', width=0.75)\n"
    "    ax.set_ylabel(metrica + ' (weighted)', fontsize=12)\n"
    "    ax.set_xlabel('')\n"
    "    ax.set_title(f'{metrica} — 3 Visões — Movies (UTLC-Movies)', fontsize=13)\n"
    "    ax.set_ylim(0, 1.0)\n"
    "    ax.legend(title='Modelo', loc='upper right')\n"
    "    ax.grid(axis='y', alpha=0.3)\n"
    "    for container in ax.containers:\n"
    "        ax.bar_label(container, fmt='%.2f', padding=2, fontsize=9)\n"
    "    plt.tight_layout()\n"
    "    slug = metrica.lower().replace('á','a').replace('í','i').replace('ã','a').replace('-','').replace(' ','')\n"
    "    pi = os.path.join(RESULTADOS, f'grafico_3_visoes_movies_{slug}.png')\n"
    "    plt.savefig(pi, dpi=150, bbox_inches='tight')\n"
    "    plt.close()\n"
    "    print(f'  - {pi}')\n"
    "\n"
    "# Mantem o grafico classico de F1 (compatibilidade com codigo antigo)\n"
    "pivot_f1 = df_resultados.pivot(index='Visão', columns='Modelo', values='F1-Score')[ordem_modelos]\n"
    "fig, ax = plt.subplots(figsize=(10, 6))\n"
    "pivot_f1.plot(kind='bar', ax=ax, rot=0, edgecolor='black', width=0.75)\n"
    "ax.set_ylabel('F1-Score (weighted)', fontsize=12)\n"
    "ax.set_xlabel('')\n"
    "ax.set_title('Comparativo das 3 Visões — Nicho: Movies (UTLC-Movies)', fontsize=13)\n"
    "ax.set_ylim(0, 1.0)\n"
    "ax.legend(title='Modelo', loc='upper right')\n"
    "ax.grid(axis='y', alpha=0.3)\n"
    "for container in ax.containers:\n"
    "    ax.bar_label(container, fmt='%.2f', padding=2, fontsize=9)\n"
    "plt.tight_layout()\n"
    "plt.savefig(os.path.join(RESULTADOS, 'grafico_3_visoes_movies.png'), dpi=150, bbox_inches='tight')\n"
    "plt.close()\n"
)

with io.open(nb_path, 'w', encoding='utf-8') as f:
    nbf.write(nb, f)
print('Notebook atualizado com gráficos para 4 métricas.')
